### ISSUE TITLE
Class 'Editor' not found 

### ISSUE THREAD

**Issue by Bredouard** [mastervanleeuwen/J-TrackGallery#10]
If I want create or edit Categories I got the following error message: Class 'Editor' not found 

J!Track Gallery 0.9.33.
Joomla version is 3.10.3

**Comment by mastervanleeuwen** [comment]
Thanks for the report. This bug was introduced when adding Joomla 4 support. It should be fixed in this version:
https://github.com/mastervanleeuwen/J-TrackGallery/archive/refs/tags/0.9.33a.zip

Could you try this version and let me know in case it does not work?

Best regards, Marco.

**Comment by Bredouard** [comment]
Hi Marco,

Thanx, it works now.

Nice job.

cu

Eddy

Am Do., 2. Dez. 2021 um 23:14 Uhr schrieb Marco van Leeuwen <
***@***.***>:
