### ISSUE TITLE
Modules

### ISSUE THREAD

**Issue by stay4you** [mastervanleeuwen/J-TrackGallery#12]
Hi
I have uplodaed j-trackgallery and all seems well, but I am unable to locate the modules or plugin.

**Comment by mastervanleeuwen** [comment]
Thanks for the report. You are right, the packaging mechanism on github does not (yet) deal with the modules and plugins. I have created and uploaded a package file:
https://github.com/mastervanleeuwen/J-TrackGallery/releases/download/0.9.33c/package_jtg.zip
Could you try and let me know whether this works?

Note that the main functionality of J!TrackGallery is in the component; the modules and plugin are providing specific additional functionality. Are you interested in some specific functionality? The documentation is rather limited at the moment, so don't hesitate to ask if something is not clear.

**Comment by LOM44** [comment]
i'm with joomla 4 ans i can't install module or plugin manifest error ...

**Comment by mastervanleeuwen** [comment]
Hi, which file did you use? 

There are several different files on the Release page:

https://github.com/mastervanleeuwen/J-TrackGallery/releases/tag/0.9.34-rc4

If you only need the component itself, use com_jtg.zip. This normally works for me. If it does not work, could you post the error message?

**Comment by mastervanleeuwen** [comment]
This seems to be resolved. Please reopen or open a new ticket in case the problem persists.
