### ISSUE TITLE
About some bugs...

### ISSUE THREAD

**Issue by sergpnm** [mastervanleeuwen/J-TrackGallery#16]
Dear Marco,
First, let me thank you for creating such a functional component. I've been looking for something like this for a long time.
In the process of testing it, I found several bugs that I would like to inform you about:
1. If I uploaded a track longer than 1000 km (for example, for the entire time of a multi-day trip), then in the "GPS Track Details" section its length is displayed as 1 km.
![image](https://user-images.githubusercontent.com/98953295/152649892-88711ce1-b89f-44ab-9ab7-77489dcdca00.png)

2. If you select a category for the overview that contains only 1 track, then the overview map is shown with a smaller scale. It looks very strange and it takes a long time to change the scale of the map to make it clear what happened. For example next link:
http://www.x-tracks.ru/index.php/otchety/spravka/treki/jtg/map?cat=20
3. In the Admin panel in the "Tracks" section, the "Hide" and "Show" buttons do not work. To hide or show some track, you need to enter its properties.
4. Map layer "OSM Hike and Bike" is not displayed. Only the gray layer is visible.
5. If several activities are indicated in the track properties (for example: cycling and rafting), then the table in the "GPS Tracks" section does not look quite correct.
![image](https://user-images.githubusercontent.com/98953295/152650165-5e4d20e6-af4f-42f8-a1a4-51c2d08c8245.png)

6. Errors in the display of some tracks. Please, see link:
http://www.x-tracks.ru/index.php/otchety/spravka/treki/track/29

I started translating the component into Russian. If you want I can post it for public access.
Thank you for your work!

**Comment by mastervanleeuwen** [comment]
Hi,

Thanks for your message! I am in the process of fixing the problems that you are pointing out and will post here again once I am done. 

Thanks for the pointer to open Topomap; I will add it as an option to the next version. You can already add/configure it for your website if you like: there is a menu item 'maps' for JTrackGallery in the administrator menus, where you can add a map. These are the settings for Open Topomap:
<img width="942" alt="image" src="https://user-images.githubusercontent.com/23643853/153663303-00453cca-e367-4ec2-9ccd-76c4e8168cba.png">

For the 'hike and bike map' it looks like this is not available anymore, but they are looking for new administrators/caretakers, see http://www.hikebikemap.org/  , so I'll keep it around as an option and remove it if it does not come back on line.

Great to hear that you are working on a Russian translation! I would be happy to add it to the public version when you are done.

Best regards, Marco.

**Comment by mastervanleeuwen** [comment]
Hi,

A new version which fixes most of problems that you found is now available here: 

https://github.com/mastervanleeuwen/J-TrackGallery/releases/download/0.9.34-rc2/package_jtg.zip

The icons in the list view are still a bit messy; I have removed a constraint on the width of the column with the icons, so that the browser can decide on the layout of the table. With all columns active, the table is too wide for a typical browser window, so there will still be some line-wrapping.

Let me know if you run into anything else. I like the suggestions in you other post and plan to implement most of them, but that may take a bit more time.

Best regards, Marco.

**Comment by sergpnm** [comment]
Hi, Marco!
I have finished the translation into Russian.
Here are the language files:
[component.zip](https://github.com/mastervanleeuwen/J-TrackGallery/files/8107501/component.zip)
[administrator.zip](https://github.com/mastervanleeuwen/J-TrackGallery/files/8107503/administrator.zip)
Best regards, Sergey Ponomarev.

**Comment by sergpnm** [comment]
Hi, Marco!
Some more bugs:
- After updating from the link above, the following problem began to be observed. There is a problem with displaying custom symbols for waypoints on a map with a multi-day track. It seems to me that the waypoint symbols are displayed correctly with the right symbol once, at the beginning of the track. After that, all symbols become of the same type (unknown type). For example: http://www.x-tracks.ru/index.php/otchety/spravka/treki/track/23

- As I understand it, when using the J-TrackGallery, green and red flag symbols are automatically added to the beginning and end of the track on the map. It seems to me that adding these symbols is better done as an additional option. This is good in cases where the user has uploaded a track that already contains some waypoints at the beginning and end of the track, or if the user wants to illustrate the beginning and end of his track with other symbols.

- On the map, when displaying the properties of a waypoint, two letters 'ca.' are displayed near to the height value. I wanted to ask if they have any meaning? If so, we need to think about how to translate them into other languages.
![image](https://user-images.githubusercontent.com/98953295/154937127-40d23355-6a0a-4f31-8341-48d8eb922969.png)

- When you create a menu item with a map and tracks of the one category, the category variables are displayed in the category drop-down list, but not the category names.
![image](https://user-images.githubusercontent.com/98953295/154939434-b43fdced-c268-4ed2-ba84-6369b13458b4.png)

- When you go to the track properties from the Admin panel, the names of variables are displayed next to the 'Calculated Values' construction site:
![image](https://user-images.githubusercontent.com/98953295/154940104-3a0cf454-44a3-4d76-8a28-0faf8d2039be.png)

Best regards, Sergey Ponomarev.

**Comment by mastervanleeuwen** [comment]
Dear Sergey,

Thanks for the Russian translation files! 

I have released a new version:  https://github.com/mastervanleeuwen/J-TrackGallery/releases/tag/0.9.34-rc4
which includes the translation files together with fixes for most of the problems that you found, including the issue with the incorrect ('unknown') waypoint icons.

You are right about the green and red start and stop markers: those are added by default for each 'track' (a single gpx file can contain multiple tracks). I agree that this could be optional/configurable; I plan to implement a setting for this in the near future.

Best regards, Marco.

**Comment by mastervanleeuwen** [comment]
Dear Sergey,

The new release here: https://github.com/mastervanleeuwen/J-TrackGallery/releases/tag/0.9.34 has the Russian translation and fixes for the problems that you identified. Please open a new issue in case you have further suggestions or if you run into a new problem.

Best regards, Marco.
