### ISSUE TITLE
Map Module

### ISSUE THREAD

**Issue by stay4you** [mastervanleeuwen/J-TrackGallery#18]
Hi would it be possible to develop a module that would show a specific position and the tracks that are available in that area.

  Thanks

**Comment by mastervanleeuwen** [comment]
Hi, yes, this is fairly easy to implement. 

I have a few questions before working on it, though:
- Do you want this to be a module, or would a 'menu item', i.e. a page from the component also work for you? The latter would be simpler to implement; we already have the 'default view' and the 'map view' which presents the map with all trails and I could add the option to center on a given position there.
- How would you specify the position to center on? The easiest to implement is if you directly input the latitude and longitude numerically as configuration options for the module. Is that what you have in mind?
- Similarly for the area to show: I would suggest to use the openlayer 'zoomlevels' or resolution parameters for this. How finely do you want to be able to control this?

Best regards, Marco.

**Comment by mastervanleeuwen** [comment]
I have implemented this as a set of configuration options for the 'Overview map' menu item, which allows to add many items in Joomla that show the main overview map centered on a specific location in this release: https://github.com/mastervanleeuwen/J-TrackGallery/releases/tag/0.9.34-rc5 

Please let me know if this works for you. It would also be straightforward to create a Joomla module with similar functionality. I think the advantage of having this as a module is that it can be shown in any given location on the page layout, together with another component. Let me me know if this is indeed what you need/are looking for.

**Comment by stay4you** [comment]
Hi
I have added a menu link via geoposition to show tracks in a certain area as at https://www.stay4you.com/drumnadrochit-tracks which I beleive will provide the required information.
But after I uploaded the latest release the maps are no longer showing can you advise.
  Thanks

**Comment by mastervanleeuwen** [comment]
Hi, thanks for trying this out. I had a quick look at your site and the problem seems to be that it is not loading/requesting one of the needed javascript files. I don't understand yet why this is, though; it may take some additional steps to debug this.

Just to be sure: which type of menu item are you using? There are two similar ones, and it is important that you pick the 'Overview map (welcome page)' and not 'Overview map'. Apologies if this is confusing; I will remove the old menu item in the next release.

Best regards, Marco.

**Comment by stay4you** [comment]
Hi thanks for getting back so quick I have set the menu to Overview welcome page.
  Thanks

**Comment by mastervanleeuwen** [comment]
Hi, I need a bit more information to debug this. Could you install the attached version of the package and reload the page? The information that I need will be printed to the php log file, which is normally called  'error_log' in your main web site directory. Could you have a look at this and send the last 10 or so lines to me, so I can use that to try and understand what is happening? If you are not sure where to find the 'error_log', I can also change the code to print the log messages directly on the page instead.
[com_jtg.zip](https://github.com/mastervanleeuwen/J-TrackGallery/files/8511472/com_jtg.zip)

**Comment by stay4you** [comment]
/home/highlan3/stay4you.com/jomres/libraries/jomres/classes/jomres_currency_exchange_rates.class.php(69): jomres_currency_exchan in /home/highlan3/stay4you.com/libraries/cjlib/vendor/guzzlehttp/guzzle/src/Utils.php on line 113
[19-Apr-2022 10:32:13 Europe/London] jtg view, calling parseMap
[19-Apr-2022 10:32:13 Europe/London] Load ol.js etc
[19-Apr-2022 10:32:13 Europe/London] done loading
[19-Apr-2022 10:32:13 Europe/London] jtg/default view; adding javascript files, e.g.: /components/com_jtg/assets/js/geolocation.js
[19-Apr-2022 10:33:25 Europe/London] jtg view, calling parseMap
[19-Apr-2022 10:33:25 Europe/London] Load ol.js etc
[19-Apr-2022 10:33:25 Europe/London] done loading
[19-Apr-2022 10:33:25 Europe/London] jtg/default view; adding javascript files, e.g.: /components/com_jtg/assets/js/geolocation.js
[19-Apr-2022 10:34:16 Europe/London] jtg view, calling parseMap
[19-Apr-2022 10:34:16 Europe/London] Load ol.js etc
[19-Apr-2022 10:34:16 Europe/London] done loading
[19-Apr-2022 10:34:16 Europe/London] jtg/default view; adding javascript files, e.g.: /components/com_jtg/assets/js/geolocation.js
[19-Apr-2022 10:34:17 Europe/London] jtg view, calling parseMap
[19-Apr-2022 10:34:17 Europe/London] Load ol.js etc
[19-Apr-2022 10:34:17 Europe/London] done loading
[19-Apr-2022 10:34:17 Europe/London] jtg/default view; adding javascript files, e.g.: /components/com_jtg/assets/js/geolocation.js

**Comment by stay4you** [comment]
Hi the issue seems to be with Google Chrome as the maps are showing on Bing.

**Comment by mastervanleeuwen** [comment]
Hi, the log messages look fine to me, which unfortunately does not help much to pinpoint the problem.

I just reloaded the page and now it works for me both on Chrome (on a Mac) and Safari. If you look at the page with 'view source', it is loading the correct JavaScript files now:
```	
        <script src="/media/com_jtg/js/openlayers/ol.js" type="text/javascript"></script>
	<script src="/components/com_jtg/assets/js/jtg.js" type="text/javascript"></script>
	<script src="/components/com_jtg/assets/js/geolocation.js" type="text/javascript"></script>
	<script src="/components/com_jtg/assets/js/jtgOverView.js" type="text/javascript"></script>
```
this was missing earlier, but I do not quite understand why...

Best regards, Marco.
