### ISSUE TITLE
Copyright link

### ISSUE THREAD

**Issue by stay4you** [mastervanleeuwen/J-TrackGallery#19]
Hi 
Can the J-TrackGallery link be romoved? I am happy to make a payment if required!

  Thanks

**Comment by mastervanleeuwen** [comment]
Hi,

This can be switched off using the 'Show J!TrackGallery credit'  switch in the configuration menu (under  'Global configuration' -> 'Jtrackgallery' -> 'Basic configuration' tab). If you set this to 'no', the 'Powered by J!TrackGallery' link at the bottom of the page is suppressed.

Hope this helps, Marco.
