### ISSUE TITLE
Incorrect link

### ISSUE THREAD

**Issue by stay4you** [mastervanleeuwen/J-TrackGallery#20]
Hi 
The correct url link to track 19 is /track/19 but the links on most popular tracks and latest tracks pint to /files/file/18

**Comment by mastervanleeuwen** [comment]
Thanks for the report; this was an old url format. I have fixed it in the development version which will be released soon.

Just to make sure: do you find that the current links are not working? In principle, this is expected to be caught in the code and redirected to the new link.

**Comment by mastervanleeuwen** [comment]
This should be fixed in the new release:

https://github.com/mastervanleeuwen/J-TrackGallery/releases/tag/0.9.34

please re-open the ticket in case you still find problems.
