### ISSUE TITLE
500 Error

### ISSUE THREAD

**Issue by mobielbas** [mastervanleeuwen/J-TrackGallery#21]
![image](https://user-images.githubusercontent.com/49426900/168589623-9d49fe4e-67dc-4277-a515-98b2bb3dcd65.png)
When i select one of the tracks: "**latest tracks**" or "**most popular tracks**" is get this 500 error. The tracks exist in their default folder. And when i click on the map it is no problem it opens as it should. Any idea where i can find the solution to this problem?

**Comment by mastervanleeuwen** [comment]
Hi, 

That is unexpected. Which version of J!TrackGallery are you using? Did you take the latest one here:
https://github.com/mastervanleeuwen/J-TrackGallery/releases/tag/0.9.34-rc5

Could you have a look at the link address and let me know what it looks like? It should end in 'index.php/component/jtg/track/<number>' where <number> is a numerical track id (../jtg/files/file/<number> is an older format that should in principle also work. 

Does your website use a subdomain, i.e. is there a piece after the main domain name, with an additional slash, like e.g. www.mywebsite.net/testing ? That should normally work as well, but maybe something was overlooked in the code for that case.

You could also have a look here at the demonstration web site: https://jtrackgalleryj4.gta-trek.eu/ for comparison.

Let me know what you find.

**Comment by mobielbas** [comment]
Thanks for your quick reaction. My website doesn't have a subdomain. When i install the latest version from your github link the map isn't visible anymore but "latetest tracks" and "most popular tracks" are working. (My first install was from this website: https://extensions.joomla.org/extension/j-trackgallery/)

**Comment by mobielbas** [comment]
Yes, that did the job! Thanks!
