### ISSUE TITLE
Unable to install modules on Joomla 4.1.4 Stable with PHP 8.1.2

### ISSUE THREAD

**Issue by wiwi0032** [mastervanleeuwen/J-TrackGallery#23]
Hi Marco, 

This project is very interesting, thank you already for your nice job and all the time you spent to keep this project up-to-date. I have downloaded the latest RC5 version. No problem to install the component and the plugin in Joomla 4.1.4. I wanted also to install the two modules but I get an error message 'Undefined constant "JPATH_"'. Any clue to find a workaround ?

Same problem as described in this article ?
https://issues.joomla.org/tracker/joomla-cms/35778

Thanks in advance.

Didier.

**Comment by mastervanleeuwen** [comment]
Hello Didier,

Thanks for the clear report, with solution. 

I tried to reproduce this on my test server with Joomla 4.1.4 (https://jtrackgalleryj4.gta-trek.eu/index.php/component/jtg/files/file/30), and did not get the error message. I will anyways try to make some of the suggested changes, just in case. I am not sure about how to set/derive the the correct name space, though...

Best regards, Marco.
