### ISSUE TITLE
Warning message when using the plugin

### ISSUE THREAD

**Issue by cogulobi** [mastervanleeuwen/J-TrackGallery#24]
Hi Marco,
I'm testing J-TrackGallery  on Joomla4: quite impressive! It is nice to have something working out of the box.
I tried to use the plugin, so as to add a track to an article. The map appears but I get a  list of warnings on the top of the page like the following one:

Warning: Use of undefined constant imap - assumed 'imap' (this will throw an Error in a future version of PHP) in /opt/lampp/htdocs/leviedellatransumanza4/plugins/content/jtrackgallery_maps/jtrackgallery_maps.php on line 233

I think it can be an issue. I'm using the most recent version of the package if have found on GitHub.

Best regards,
Corrado

**Comment by mastervanleeuwen** [comment]
Hi Corrado,

Thanks for the report; this was indeed a problem in the code; in my testing version the messages only showed up in the error_log, so I had not noticed, but I fixed the problem and re-released 0.9.34. Can you try with this version:
https://github.com/mastervanleeuwen/J-TrackGallery/releases/tag/0.9.34
(you only need to reinstall the plugin part)

Please let me know if you still see the errors.

Best regards, Marco.

**Comment by cogulobi** [comment]
HI Marco,
I installed just the plugin and I can confirm the problem is solved.
Thank you.
Corrado
