### ISSUE TITLE
maps plugin not displaying images

### ISSUE THREAD

**Issue by DavidJRichards** [mastervanleeuwen/J-TrackGallery#27]
Greetings Marco,

The map plugin does not seem to work properly, or at least not like a direct display of a map from the main menus.
The map shows with the camera icons but clicking on the camera icon does not show the associated image, in a page called from the main menus then clicking on a camera icon shows the associated image.

Also, something for another issue ... I cannot get the plugin show height parameter to work although it is possible to use the admin menu to change the map height. Using it can stop the map from displaying completely.

Hope you don't mind, do you want all issues reporting here?
The above problems are not causing me any problem at present.
Kind regards, David.

**Comment by mastervanleeuwen** [comment]
Hi David,

The map plugin is meant to display a map in an article or from another component. If you want to display a GPS track from the main menu, you can also try to use the track view; this will however show the full page with the statistics and description etc. See for example this page:
https://testing.gta-trek.eu/index.php/nl/north-york-moors-track
(accessible via the menu item 'New York Moors track' in the menu on the right).

Thanks for pointing out the other issues as well (and for indicating that they do not cause problems for you at this point); I had a look and I will be able to fix the issues with the popups, but need a bit more coding and testing to make it work with multiple maps on a single page.

Setting the height of the map does work for me, see this test page:
https://jtrackgalleryj4.gta-trek.eu/index.php/en/plugin
where I tried both setting the height via the plugin configuration and setting it via an argument to the plugin (`map_height=500px` for the upper map). Maybe there is something about your specific use case that makes it fail? Could you check in the html source whether you see something like this:
```
#jtg_map_1.olMap {
   height: 500px;
   width: 100%;
   z-index: 0;
}
```
with the correct height specified?

Don't hesitate to report any other issues that you might find; that is the quickest way for me to find out about them.

Best regards, Marco.

**Comment by DavidJRichards** [comment]
Hi Marco, I'll do some more testing of the plugin parameters. Should I be adding the 'px' suffix to the height values on the plugin invocation?

I'm missing some basic understanding, how do I create a menu item with just one map like your North York moors example? Btw that location is just a few miles from my home.

Kind regards, David

**Comment by DavidJRichards** [comment]
Adding px to the height value has made the feature work for me, great. Thanks for the help, David.

**Comment by mastervanleeuwen** [comment]
Dear David,

You can create a menu item that shows a single track, like the North York moors example, by going to menu management page, creating a new item, and then choosing 'Menu Item type'; this will bring up a menu with entries for several Joomla components and J!TrackGallery should be in the list; if you choose that item, this list will appear:

<img width="1169" alt="image" src="https://user-images.githubusercontent.com/23643853/179424740-20725316-1453-4bd9-8858-e74d9665dd6e.png">

where you can select 'Track'. After chosing this, a new field will appear 'Track', which has a drop down menu with all the tracks:
<img width="1169" alt="image" src="https://user-images.githubusercontent.com/23643853/179424855-0d82316d-cf6b-49e2-b3a8-fbe38411ca37.png">

Hope this helps. If so, I will probably add this to the documentation pages.

Best regards, Marco.

**Comment by DavidJRichards** [comment]
Thanks Marco, I'd just sussed  the method for myself when I got your email.
Attached is a geotagged photo taken at Hutton le Hole
![IMG_20160821_110935_](https://user-images.githubusercontent.com/16197914/179425193-082cd6eb-02dd-4ff7-9e7a-3b093d0f0239.jpg)
. Kind regards, David.
