### ISSUE TITLE
Problem with an administrative page

### ISSUE THREAD

**Issue by cogulobi** [mastervanleeuwen/J-TrackGallery#28]
HI Marco,
a new issue: in the administration page, if I select "categories" I get the following error

0 syntax error, unexpected ';' 

It was working before the recent updates.

Best regards,
Corrado

**Comment by mastervanleeuwen** [comment]
Hi Corrado,

Oops; I introduced a typo when fixing something  else. I thought I tested it, but clearly I did not. I have re-tagged the same version number with a fix for this:
https://github.com/mastervanleeuwen/J-TrackGallery/releases/tag/0.9.34-rc13

Regards, Marco.

**Comment by cogulobi** [comment]
Hi Marco,
the problem is solved.
Just one more detail concerning the categories voice. 
If I click the name of one of the categories  I get the 404 error. In any case it is possible to modify such category by selecting it.

Best regards and thank you again,
Corrado

**Comment by mastervanleeuwen** [comment]
Hi Corrado,

Apologies for not coming back on this sooner, but I have fixed this in the mean time; you can use a recent development version for example: 
https://github.com/mastervanleeuwen/J-TrackGallery/releases/tag/0.9.34-rc25

Don't hesitate to contact me again if the problem persists.

Best regards, Marco.
