### ISSUE TITLE
Geoposition

### ISSUE THREAD

**Issue by surferchick** [mastervanleeuwen/J-TrackGallery#3]
I am trying to get this menu setting to work, but unsure i am doing it correct, please see here: http://ridemybackyard.com.au/routes/routes-by-geo

i have set the Lat and Long, but the page is coming up blank.
I would like to set a map up for rides leaving from a particular place, for example Milano
Can i use this to set the Lon and Lat of Milan and then see all routes in that area? 

Thanks, i really like this component, its great!

**Comment by mastervanleeuwen** [comment]
Hi,
Great to hear that you like J!Trackgallery! From the description, I am not 100% sure which menu item you are trying to configure. Is this the 'geoposition' view? The code for this is probably incomplete (and has been for a while). I'll look into fixing/completing this.
Best regards, Marco.

**Comment by surferchick** [comment]
Hi Marco!
Yes it’s the geoposition menu  function
It would be great to show routes close to a particular area.
Well done on the component it’s great!  

Best Regards,
Yvette

**Comment by mastervanleeuwen** [comment]
Hello Yvette,

Thanks for the suggestion; I have added a geolocation option to the 'Overview map' menu item. You can find the new (pre-release) version here:

https://github.com/mastervanleeuwen/J-TrackGallery/archive/refs/tags/0.9.31-rc7.zip

Best regards, Marco.

**Comment by surferchick** [comment]
Hi Marco
Thanks for this, i have been away a few days, but will test immediately in the morning for you
Warm regards from Australia

**Comment by joomleb** [comment]
Hi guys, 
Should be good to deprecate/delete the _Default View with Map_ and _Geoposition_ and to keep just 1 **Overview Map** menu item, less maintenance from your part, with all the options in an ordered way, I added a detailed issue tracker here #8

**Comment by mastervanleeuwen** [comment]
Based on this suggestions, I added a geolocation button added to the map view in the current/latest version of J!Trackgallery. Hope this works for everyone. Feel free to reopen this issue if you would like to follow up
