### ISSUE TITLE
Error when selecting "My Tracks"

### ISSUE THREAD

**Issue by mobielbas** [mastervanleeuwen/J-TrackGallery#31]
Hi Marco, when i select "my tracks" i get an error:

![foutmelding jtrackgallery](https://user-images.githubusercontent.com/49426900/188847971-a6d5887a-a06a-4cc0-8a81-ea777634e10d.jpg)

And i have another problem. The background and modules from my 'home' page are visible on my 'J!trackgallery' page?

Joomla 4.2.2 and the newest version of J!trackgallery (0.9.34-rc12)

Greetings,

Bas

**Comment by mastervanleeuwen** [comment]
Hi Bas,

I do not get the getDbo() error on my test system. This function call is quite common in the code, so it would be convenient to have a line number of function name to pinpoint the cause. Could you have a look at the php log file on your web server (normally called 'error_log' in the main web directory) to see whether the error is shown there as well? There are probably also log files in administrator/log that you could check.

Concerning the modules: I think that the default behaviour of Joomla is to show active modules on all  pages, but you can select to show a specific module with specific menu items. This is done in the tab 'Menu assignment' in the module configuration. Could you try this?

I am not sure I understand what the 'backgroung' is from your home page. Do you know how this is set up? Is it part of the site template? 

Best regards, Marco.

**Comment by mastervanleeuwen** [comment]
Hi Bas,

I made a few changes to gpsClass.php to try and fix the issue you mention above. Could you try this version:
https://github.com/mastervanleeuwen/J-TrackGallery/releases/tag/0.9.34-rc14
and let me know whether it fixes the issue? Can you also try the 'my tracks' item again to see whether the problem persists? If the problem is still there, I can prepare a version with some debug printouts to try and locate the problem more closely.

For the problem with the background module, I am not sure what exactly you mean. What is the background module that you are using and what is it supposed to do? If you point me to some information on how you have set this up, I can try to reproduce it locally. Is your website online, or are you testing on a server on a local network?

Best regards, Marco.

**Comment by mobielbas** [comment]
Hi Marco,

Thanks, i will test it. I have build my site from scratch again. 

The modules i was talking about are:

https://extensions.joomla.org/extension/bgmax/

and

https://extensions.joomla.org/extension/background-video-pro/

It is a test site on a local network. And i am using the Helix Ultimate Template on Joomla 4.4.2

Greetings, Bas

**Comment by mobielbas** [comment]
I have tried your new version and it gives another failure:

![image](https://user-images.githubusercontent.com/49426900/191035510-53cabac8-346f-44d4-a603-bb3f40c790c0.png)

When i select a track. 

The background problem is still there.

**Comment by mastervanleeuwen** [comment]
Hi Bas,

I think I found the cause for this error as well and have implemented a fix in this version:
https://github.com/mastervanleeuwen/J-TrackGallery/releases/tag/0.9.34-rc15
Could you try it and let me know?

I would like to try and debug the issue with displaying a background image as well, but did not manage to get the background module to work on Joomla 4. Could you help me check the settings? I have set the location to 'debug':
<img width="342" alt="image" src="https://user-images.githubusercontent.com/23643853/192101848-3821f6a8-ac21-4b25-89b8-ce66a8b1203a.png">

And I have set the css tag:
<img width="963" alt="image" src="https://user-images.githubusercontent.com/23643853/192101893-80f144e9-ae7b-422f-9f5c-5b93e13f979d.png">

and set it to show on all pages:
<img width="555" alt="image" src="https://user-images.githubusercontent.com/23643853/192101908-9b895d77-1bc4-447a-9a05-5649718af3d1.png">

These settings (with a different css tag) work on Joomla 3.9.10 for me (see: https://testing.gta-trek.eu/index.php/nl/ ) but do not seem to work on joomla 4 (  https://jtrackgalleryj4.gta-trek.eu/index.php/en/ ). Do you know whether any additional settings are needed?

Cheers, Marco.

**Comment by mobielbas** [comment]
Hi Marco, i don't know if there are more settings needed. I have assigned it to only my 'home page'

![image](https://user-images.githubusercontent.com/49426900/193529932-7aa9271e-7623-46ce-9cbf-1e43d7f60543.png)

And in the debug position

![image](https://user-images.githubusercontent.com/49426900/193530158-25869369-9773-4cab-904e-0804820e4d01.png)

It is not the only module that is visible on my 'GPX routes' page. Also the bottom1, bottom2 and buttom 3 are visible. And they are not assigned to the 'GPX routes' page.

![image](https://user-images.githubusercontent.com/49426900/193530712-a43331b2-a111-4202-a7d8-a1a5bb5bf939.png)
 
Greetings, Bas

**Comment by mobielbas** [comment]
I forgot to tell you that the error with the tracks are gone!! Thanks!

**Comment by mastervanleeuwen** [comment]
Hi Bas,

I looked a bit more into the bgMax module, and realised that there may be some additional setting under: 'Conditional display' and 'Criteria' that may be needed to select a specific menu item.

I could not fully test it on my page, because it does not quite work; the image shows up at the bottom of the page instead of the background. Still, it seems that controlling the menu items where it should be displayed works for me.

Could you try with the 'J!TrackGallery - recent tracks' module whether the menu item selection works for you in that case? I have tested it on my page here: https://jtrackgalleryj4.gta-trek.eu/index.php/en/about and there it works: I configured it to  show up only at the 'about' page and with the 'J-Trackgallery' menu item, but not with the others.

Best regards, Marco.

**Comment by mobielbas** [comment]
Hi Marco,

The 'J!TrackGallery - recent tracks' are working fine for me. The only problems are still the modules i have assigned to my "Home" page are still visible on my 'GPS routes' page which are show above. Not only the 'BgMax', but also my custom modules on the bottom of the page. On positions: Bottom1, Bottom2 and Bottom3. As a test i have assigned the BgMax background to another made page with weblinks and this is not visible on my 'GPS routes' page. 
Summarizing: the modules (all) asigned to my 'Home' page are all visible on my "GPX routes" page.

Greetings

Bas

**Comment by mobielbas** [comment]
Hello Marco,

I have tested with a newly build joomla page. I have the standard template of Cassiopeia. I have found out that the standard map link in the menu works ok. But when i select a track it redirects to my home page.

![gpx-1](https://user-images.githubusercontent.com/49426900/211489468-5b978286-5c45-46ab-a0dd-513bf76a94ed.jpg)

With the map it works oke as you can see

but... when i open a **track**!

![gpx-2](https://user-images.githubusercontent.com/49426900/211489578-435461af-3819-4c32-a7e0-c6d2ed537346.jpg)

Here you can see it redirects to my homepage???

I am very sure that i did not assign jtracks to my homepage

![gpx-3](https://user-images.githubusercontent.com/49426900/211490179-8fc7e76f-088d-45d6-93f8-dfb5925e8eff.jpg)

I hope that you can help me with this. 

Greetings 

Bas

**Comment by mastervanleeuwen** [comment]
Hi Bas,

Thanks for the report. I have been working on improving the 'router' which I think will improve this behaviour. Could you try the new version:
https://github.com/mastervanleeuwen/J-TrackGallery/releases/download/0.9.34-rc25/com_jtg.zip

and let me know whether the links behave as expected now?

Best regards, Marco.

**Comment by mobielbas** [comment]
Hi Marco,

Yes this is it! Everything is working perfect now! When i open the track it does not show any modules from the homepage anymore!

Thank you very much for your support,

Bas
________________________________
Van: Marco van Leeuwen ***@***.***>
Verzonden: dinsdag 10 januari 2023 21:11
Aan: mastervanleeuwen/J-TrackGallery ***@***.***>
CC: mobielbas ***@***.***>; Author ***@***.***>
Onderwerp: Re: [mastervanleeuwen/J-TrackGallery] Error when selecting "My Tracks" (Issue #31)


Hi Bas,

Thanks for the report. I have been working on improving the 'router' which I think will improve this behaviour. Could you try the new version:
https://github.com/mastervanleeuwen/J-TrackGallery/releases/download/0.9.34-rc25/com_jtg.zip

and let me know whether the links behave as expected now?

Best regards, Marco.
