### ISSUE TITLE
Unable to change J!Track configuration in J4

### ISSUE THREAD

**Issue by RalfKausK** [mastervanleeuwen/J-TrackGallery#33]
Hi
I have a **Joomla "4.2.3"** installed and running with J!Track Gallery (J!Track Gallery current installed version: | **0.9.34**)
But, I'm not able to change the configuration due to an issue.
No matter if I go to Menu -> Component -> J!Track Gallery -> Configuration or System -> Global configuration -> J1Track Gallery to change the default settings, the shown page is messed up.
I can see the configuration content without the left-hand-menu. The menu is embedded below the whole config (see picture) and displays error: 
` htmlspecialchars(): Argument #1 ($string) must be of type string, array given`
Is this an known issue?  Can you solve it?

P.S.: I new to joomla wed-design, so please be patient :)

Best regards
Ralf

![Bildschirmfoto vom 2022-10-25 12-59-14](https://user-images.githubusercontent.com/116641151/197756848-1757f17d-a2f2-4c80-833d-784652bcc5e5.png)

**Comment by mastervanleeuwen** [comment]
Hi Ralf,

Have you tried to download the latest version of J!TrackGallery from this link: https://github.com/mastervanleeuwen/J-TrackGallery/releases/download/0.9.34-rc18/mod_jtrackgallery_latest.zip
(on the release page: https://github.com/mastervanleeuwen/J-TrackGallery/releases/tag/0.9.34-rc18 )

The version posted on the Joomla extension directory is older and some bugs have been fixed in the mean time.

Best regards, Marco.

**Comment by RalfKausK** [comment]
Hey Marco

To avoid any compatibility problems I thought it might be the best option to choose the Joomla repository version.
But if you mention to better use the github version I'll give it a try and update this issue afterwards.

Best Regards Ralf

**Comment by RalfKausK** [comment]
I decided to start with a brand new Joomla version.
After the installation finished an update to 4.2.4 was available, which I installed.
Afterwards I tried to install the component version from the repository again but ran into multiple errors

`JInstaller: :Install: Die Datei „[ROOT][TMP]/install_63599cfb6d719/install_63599cfb7405e/language/nl-NL/nl-NL.mod_jtrackgallery_latest.ini“ existiert nicht.
JInstaller: :Install: Die Datei „[ROOT][TMP]/install_63599cfb6d719/install_63599cfb8c9a1/language/nl-NL/nl-NL.mod_jtrackgallery_stats.ini“ existiert nicht.
JInstaller: :Install: SQL-Fehler Incorrect foreign key definition for 'foreign key without name': Key reference and table reference don't match
Installation der Erweiterung abgebrochen.
Paket Installieren: Bei der Installation der Erweiterung trat ein Fehler auf: com_jtg.zip`

The module zip file link you provided was installed without errors.
But from what I can see it's an module and the repository installation includes a component. Am I right that just the module is not enough and I also need the component installation?
Any idea?

**Comment by mastervanleeuwen** [comment]
Dear Ralf,

The main functional part of the code is in the com_jtg.zip file. Could you
try to install that one? I will also look into the installation error that
you are getting for the 'statistics' module (one of the language files
seems to be missing), but most of the functionality is there without using
the module.

Best regards, Marco.

**Comment by RalfKausK** [comment]
Hey Marco

I used the option to install with URL in Joomla.
Source: https://github.com/mastervanleeuwen/J-TrackGallery/releases/download/0.9.34-rc18/com_jtg.zip

Error:
`JInstaller: :Install: SQL-Fehler Incorrect foreign key definition for 'foreign key without name': Key reference and table reference don't match
Installation der Erweiterung abgebrochen. (= canceled)`

**Comment by mastervanleeuwen** [comment]
Hi Ralf,

It seems that your data base engine is more picky than mine. Could you try with this version:
https://github.com/mastervanleeuwen/J-TrackGallery/releases/download/0.9.34-test/com_jtg.zip
I made a change in the script that seems to be causing the issue, but I cannot easily test it on my system, since it worked there without the change as well.

If it fails again, could you check whether there is an 'error_log' file in the 'administrator' directory on your web server, and see whether it contains a longer error message?

Best regards, Marco.

**Comment by RalfKausK** [comment]
Hey Marco
This version works fine for me. No errors nor complains.
Just a success message.
Now I have to figure out how to use and customize it for my requirements.
Thank you, I appreciate your good and fast support :)

![grafik](https://user-images.githubusercontent.com/116641151/198714466-30c6fdf5-f7ac-4d73-9757-4fd36bebbc04.png)

Best regards
Ralf

**Comment by mastervanleeuwen** [comment]
Hi Ralf,

Thanks for the feedback; great to hear that it works now. I will include this change in the next release.

I'll close this issue. In case something else pops up, feel free to start a new thread.

Best regards, Marco.
