### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by Sittbrunnen** [mastervanleeuwen/J-TrackGallery#34]
I have installed the plugin, made a folder in public_html called gpx, where I have placed my Rundrutten2.gpx
In an article I have written
{JTRACKGALLERYMAP} gpxfilename=Runtrutten2.gpx, show_link=1 {/JTRACKGALLERYMAP}
but the article only shows that code.
https://sittbrunnen.se/havsbiblioteket/hafsorkestern
I have tryed to find out by reading the documents, but I do not understand what I have done wrong. Could you please help me.
Niklas

**Comment by mastervanleeuwen** [comment]
Dear Nilkas,

The plugin only works together with the main component, so you have to
install com_jtg.zip as well. You can then upload the gpx file into the
J!TrackGallery component (in the admin view, or from the frontend) and then
you can display the track as you tried above (make sure to use the correct
file name Rundrutten or Runtrutten?).

You can find the latest versions of the component and plugin here:
https://github.com/mastervanleeuwen/J-TrackGallery/releases/tag/0.9.34-rc19
. Please make sure to use the same release for both the component and the
plugin; I have recently been working on some of the code that is shared
between them, so matching versions are required.

Best regards, Marco.

**Comment by Sittbrunnen** [comment]
Dear Marco
I now have installed all the files, but the source code, and no change.
Filename checked.
Regards
Niklas

**Comment by mastervanleeuwen** [comment]
Hi Niklas,

Strange, it looks like the plugin code is not called at all. Have you enabled/published the plugin? 

I think the track is uploaded correctly, you can see it here: https://sittbrunnen.se/component/jtg/track/17  but there seem to be javascript errors (maybe in code that is associated with your template?) and I also see some errors like this: 

Refused to load the stylesheet 'https://fonts.googleapis.com/icon?family=Material+Icons' because it violates the following Content Security Policy directive: "default-src 'self' 'unsafe-inline'". Note that 'style-src-elem' was not explicitly set, so 'default-src' is used as a fallback.

which asre not familiar to me. I wonder whether they are a side-effect of the other errors, or whether something more is going on.

Best regards, Marco.

**Comment by Sittbrunnen** [comment]
Hi Marco
I found where to publish the plugin, and something changed, but it still not works. Now I get error message
J!TrackGallery plugin: Specified track not found ( id=null gpxfilename=Runtrutten2.gpx)
The correctly uploaded track was for the test module I published, not for the article code.
Regards
Niklas

**Comment by Sittbrunnen** [comment]
Hi again Marco
When activated I found how to import gpx files. Wich gives a new problem: It is not at track, but a route, I want to publish. The route I have been sailing around the world. 
Is that possible, or am I trying to use the wrong plugin?
Regards
Niklas
![Runtrrutten2](https://user-images.githubusercontent.com/120041068/206528233-52638c28-fdaa-4bcf-a7ca-512cdc49ed3d.jpg)

**Comment by mastervanleeuwen** [comment]
Hi Niklas,

The code should be able to show a route, but it is not tested as well with routes as it is with tracks. It could also be that the fact that the route spans the whole world is causing a problem. The easiest for me is if you could send me the gpx file (e.g. by adding it here as an attachment, or by direct e-mail to my gmail address), so that I can test it and debug the gpx file parsing if needed. Would that be OK?

Best regards, Marco.

**Comment by mastervanleeuwen** [comment]
One more thing, the 'id=null' in the warning message, means that the code cannot find the track in the database. When I look at the track list here:

**Comment by Sittbrunnen** [comment]
Hi again Marco
I solved one problem by search and replace, changing the route to a track in the xml. But the date line is still a problem.
https://sittbrunnen.se/havsbiblioteket/hafsorkestern
Could I separate the track into two, by dateline, and show them in one map view? (Nice would be in two different colours.)
Anothe issue: I managed to choose Google map in the module, but not in the article.
Niklas

**Comment by mastervanleeuwen** [comment]
Hi Niklas,

Thanks for following this up. There is no easy way to show two tracks with
the plugin at the moment. I can look into adding this possibility, but it
will take some time.

Concerning google maps: this is more difficult: the plugin and component
use the openlayers javascript library to show tracks and maps; this works
with different variants of the openstreetmaps and with Bing, but Google
only allows use of their maps via their own code interface (API). Could you
try with one of the open maps? I have good experiments with the 'openycle'
map, and also with the open topomap. There may also be specific marine maps
that use the openstreetmap platform.

Something else: when I look at your site
https://sittbrunnen.se/havsbiblioteket/hafsorkestern with Google Chrome,
the map is not shown properly and  I get several security warnings (in the
developer tools view). There is security warning when trying to load the
jquery code in this line:

<script src="
https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js" type="
text/javascript"></script>

line 37 in the source view, which breaks some of the other javascript code.
Do you why it is loading jquery from the googleapi server? There is also a
built in jquery with Joomla, I think. Which version of Joomla are you using?

Best regards, Marco.

**Comment by Sittbrunnen** [comment]
Hi Marco
I created the googleapi tu use in your module, so I guess that one is the problem. I have now depublished the module, so if the error is still there, something else causes it.
I had a problem, when launching chrome. My Cookiehint plugin stopped the second JTG map, until I clicked OK in the bottom. But that should not stop googleapi. Will not appear again in 365 days.
I am running J 3.10, PHP 7.4, trying to get ready for J4, but have to change template before, and get rid of some old stuff. If you need a login, send a private mail.
Regards
Niklas

**Comment by mastervanleeuwen** [comment]
Hi Niklas,

Could you try this version of the jtg component: https://github.com/mastervanleeuwen/J-TrackGallery/releases/download/0.9.34-rc20/com_jtg.zip

it contains a small change that removes the use of jQuery in parts of the J-TrackGallery code. I hope that with this change, the maps will render correctly on your webpage.

You page is still trying to load jQuery from the googlapi servers instead of using the version that comes with Joomla and is installed on you web server. I am not sure why it does that, maybe the template code, or one of the other modules/components uses this?

Best regards, Marco.

**Comment by Sittbrunnen** [comment]
Hi Marco
Running that version now. Cant see any difference. Date line is still not working.
I do not know why the load from Googleapi comes. I will try to change to another template that works with J4, but I am into some problems there too.
I think I need to do some cleaning up.
Regards
Niklas

**Comment by Sittbrunnen** [comment]
Hi Marco.

Thanks, now it works.

First I tryed with one track file (runtigen.gpx) with two segments, divided by the dateline. This only showed the first segment, but both green and red flags in Stockholm.  Then I switched to my first version (Runtny.gpx), with only one segment, witch went fine.

Would it be possible two show different segments, in different colours? (Now they mix much back in Europe.)

Can I change colour of the track, to green or red?

How do I change map style for the files, showing with the article code? Do I have to import them again?

Concerning CSS problems, I have found out it is major problems with the template. JA Puresite does not support J4, neither PHP8. Maybe not even J3.10 I am running now. So I am trying to migrate to something else, maybe JA Purity III, to be able to upgrade the site to J4. So hopefully thoose problems will disapear by then.

Many thanks

Niklas

**Comment by Sittbrunnen** [comment]
Hi again Marco.
I am sorry, but now the date line bug is back again.
I might have caused it, because I hade to restore the site from backup, after another installation mistake. But I have reinstalled your version above, and it does not work.
Niklas

**Comment by mastervanleeuwen** [comment]
Dear Niklas,

I looked at your site and for me it seems to work: 
<img width="755" alt="image" src="https://user-images.githubusercontent.com/23643853/208246034-bb52b3f5-82d8-42ca-8a66-7832bdeaf532.png">

you may have to reload with alt-shift-R to make sure that the JavaScript is reloaded.

If you look closely, there is some kind of artefact at the date line; I messed up the interpolation and I think it should be fixed it in this version:
https://github.com/mastervanleeuwen/J-TrackGallery/releases/tag/0.9.34-rc22
Could you give that one a try?

I will also try to implement a way to set the line colors.

Best regards, Marco.

**Comment by Sittbrunnen** [comment]
Dear Marco
Yes worked after deleting history.
But the extra point between 142 and 143 is still there.
Line colors would be great. (Maybe just a little thinner line?)
Regards
Niklas

**Comment by mastervanleeuwen** [comment]
Hi Niklas,

I have added the possibility to show the track segments in different colors in the plugin. You can add an option 'colors=' with a semicolon-separated list of colors, with format '#aabbcc' (rgb in hex). The code applies the colors to subsequent segments of the track, and it splits the track on the dateline, so it should use different colors before and after the date line. You may have to experiment a bit to find out how many segments your track contains.

I used this: `{JTRACKGALLERYMAP}id=19,show_link=2, map_width=70%, map_height=500px, show_graph=1,colors=#ff00ff;#00ff00;#0000ff{/JTRACKGALLERYMAP} ` to test the code.

The new release with these features is available here: https://github.com/mastervanleeuwen/J-TrackGallery/releases/tag/0.9.34-rc23

Please made sure to update both the component code (com_jtg.zip) and the plugin code (plg_....zip).

Best regards, Marco.

**Comment by Sittbrunnen** [comment]
Thanks
This is perfect, very nice with two segments. I did install the "package". 
Around next year am I planning to migrate to J4.
Will it work with that too?
Niklas

**Comment by Sittbrunnen** [comment]
![bild](https://user-images.githubusercontent.com/120041068/208920816-2d3a0238-b77b-44e2-9351-cb8d51b27320.png)

**Comment by mastervanleeuwen** [comment]
Hi Niklas,

Thanks for the feedback; great to see that this works. 

Everything should also work with Joomla 4. I have been testing it here: https://jtrackgalleryj4.gta-trek.eu/  and as far as I can tell, everything works. Don't hesitate to contact me in case something does not work.

Best regards, Marco.

**Comment by Sittbrunnen** [comment]
Just saw something strange, When I added text above the map/code it lost my styling. Also some unused space above the map.
Niklas

**Comment by mastervanleeuwen** [comment]
Hi Niklas,

Looking at the html source, the text above the plugin is formatted with <code>:
```
<p><code class="notranslate">Här är rutten
```
and this is followed by a <pre> tag:
```
<pre class="highlight"><code><code><code><code class="notranslate"><br /><br />
```
is that something that you can control/change?

Best regards, Marco.

**Comment by Sittbrunnen** [comment]
Yes, I could manually delete, by switching to html. Thought it was something you needed.
Is there a way to upload gpx, for the users?
Niklas

**Comment by mastervanleeuwen** [comment]
Hi Niklas,

You can give users permission to upload tracks in the settings of the component, see here: https://mastervanleeuwen.github.io/J-TrackGallery/configuration.html

With this setting, users that are logged in will see an additional entry: 'Add track' in the J!TrackGallery menu (on e.g. the track or overview page). If you prefer, you can create a custom menu item and configure it to show the 'new track' upload page.

Best regards, Marco.
