### ISSUE TITLE
configurer le  plugin

### ISSUE THREAD

**Issue by perlim-pinpin** [mastervanleeuwen/J-TrackGallery#39]
Hi Marco,

Joomla4, php 8.1
j'utilise les versions suivantes :
- https://github.com/mastervanleeuwen/J-TrackGallery/releases/download/0.9.34-rc24/com_jtg.zip
- https://github.com/mastervanleeuwen/J-TrackGallery/releases/download/0.9.34-rc24/plg_jtrackgallery_maps.zip
ça fonctionne

dans un article est-il possible d'afficher les information que l'on veut ?

- avec l'option "show_info=1" afficher ce qui suit et pouvoir supprimer le reste :

distance 98.4 km
durée en mouvement 04:48:40 => est-ce possible d'avoir ce renseignement ?
moyenne en mouvement  20.5 km/h => est-ce possible d'avoir ce renseignement ?
dénivelé positif 1107 m
 
enlever ce qui est entouré ?
![Screenshot 2023-01-18 at 10-09-25 test J-trackGallery](https://user-images.githubusercontent.com/122956429/213200481-045b70a9-a8c4-4a1e-9f2d-edbd11b80a14.png)

peut- m'aider ?

Regards

**Comment by perlim-pinpin** [comment]
Hi Marco, avec la nouvelle version serait-il possible de pouvoir paramétrer dans les "informations de la trace" 

![Screenshot 2023-01-31 at 07-26-45 test J-trackGallery](https://user-images.githubusercontent.com/122956429/215683959-f2ef0657-04de-474a-8ebe-f4602b764712.png)

**Comment by mastervanleeuwen** [comment]
Thanks for the suggestion. It is now possible to configure which fields are shown in the info-section. You can also disable  the use of track categories in the settings of the J-TrackGallery component. When this is disabled, the icons are not shown in the track. These features and a few more updates can be found in the latest pre-release:
https://github.com/mastervanleeuwen/J-TrackGallery/releases/tag/0.9.34-rc40
