### ISSUE TITLE
erreur - bas de la page

### ISSUE THREAD

**Issue by perlim-pinpin** [mastervanleeuwen/J-TrackGallery#40]
Hi Marco,

en bas de la page enlever ce qui est entouré

![Screenshot 2023-01-18 at 15-47-00 Catégories - perlimpinpin](https://user-images.githubusercontent.com/122956429/213202983-a3373be1-2468-452f-bfae-b25ed5413c18.png)

regards

**Comment by mastervanleeuwen** [comment]
Hi Perlim,

Thanks for your message. Unfortunately, I am not sure where these printouts come from. It looks like it is some information about the time it takes to format the page or to run a query. A debug setting perhaps? I don't see this on my test server:

https://jtrackgalleryj4.gta-trek.eu/index.php/en/component/jtg/cats/default
https://testing.gta-trek.eu/index.php/nl/j-trackgallery/cats/default

It looks like this is printed after the signature line 'powered by J!TrackGallery', so maybe it is produced by some other module or setting?

Best regards, Marco.
(P.S.: feel free to post in French, I read some French, but do now write French well)

**Comment by perlim-pinpin** [comment]
dans un article, j'insère le code
{JTRACKGALLERYMAP}gpxfilename=2023-01-14.gpx,map_height=700px,map_width=100%,show_graph=1,show_info=1{/JTRACKGALLERYMAP}
il n'y a rien d'affiché
![Screenshot 2023-01-19 at 04-19-02 test J-trackGallery](https://user-images.githubusercontent.com/122956429/213348214-ddbb9280-f02a-44df-a4e3-5e633900b1f0.png)

mais si je clique sur l’icône "vélo" alors on voit ces informations
donc ça vient du composant
![Screenshot 2023-01-19 at 04-22-47 Fichiers GPS](https://user-images.githubusercontent.com/122956429/213348380-d475040a-0aa8-4021-bef7-ceec589692a6.png)


bonne journée Marco

**Comment by mastervanleeuwen** [comment]
Thanks for the report. I expect that the suggestion above solves the issue that you raised, so I will close this report. Don't hesitate to contact me again in case of problems or requests.
