### ISSUE TITLE
suggestions - track view

### ISSUE THREAD

**Issue by perlim-pinpin** [mastervanleeuwen/J-TrackGallery#41]
Hi Marco, 
dans l'image ci-dessous pouvoir choisir ce que l'on veut afficher...

![Screenshot 2023-01-18 at 15-51-42 Fichiers GPS - perlimpinpin](https://user-images.githubusercontent.com/122956429/213204698-08a9c9f5-c1bc-42a6-9334-65ed1c6e8cfb.png)

best regards

**Comment by mastervanleeuwen** [comment]
Hi,

Unfortunately, I don't quite understand your question/suggestion. The upper part of the page is meant to set filters, to show a list of selected tracks, for example with a minimum or maximum length. Would you like to show the list without the filter box?

Please feel free to post your question in French.

Best regards, Marco.

**Comment by perlim-pinpin** [comment]
Hi

est-il possible de paramétrer l'affichage ?
par exemple
- de choisir les filtres que l'on souhaite (en rouge)
- ne pas afficher la colonne "utilisateur" ou nombre de "vues" ou la colonne "terrain"... (en bleu)

=> donc de pouvoir paramétrer tous les filtres d'affichages (en rouge) et toutes les colonnes (en bleu)
Je pense que les deux, les filtres et le tableau, sont liés.

best regards

**Comment by mastervanleeuwen** [comment]
Hi,

Some of the columns in the track list can be switched on and off in the settings:
<img width="1058" alt="image" src="https://user-images.githubusercontent.com/23643853/213889243-b6fe73d3-4cb9-4f79-8e3c-889e11ecc396.png">
You can find this under 'global settings' in the administrator menu.

Best regards, Marco.

--------------------------------

en Francais (google translate):

Certaines colonnes de la liste des pistes peuvent être activées et désactivées dans les paramètres:
<img width="1058" alt="image" src="https://user-images.githubusercontent.com/23643853/213889243-b6fe73d3-4cb9-4f79-8e3c-889e11ecc396.png">
Vous pouvez le trouver sous 'paramètres globaux' dans le menu administrateur.

Cordialement, Marco.

**Comment by perlim-pinpin** [comment]
Hi,
même en désactivant tout, en masquant tout ce qui est possible de masquer il reste ce qui est entouré
![Screenshot 2023-01-23 at 03-32-41 Fichiers GPS - perlimpinpin](https://user-images.githubusercontent.com/122956429/213957145-55130123-6b62-4d86-a383-95992aeee270.png)
regards

**Comment by mastervanleeuwen** [comment]
Hi Marco,

I have added a new version here:
https://github.com/mastervanleeuwen/J-TrackGallery/releases/tag/0.9.34-rc26
which allows to disable the use of the difficulty level with a setting in 'components'->'J!TrackGallery'->Configuration and then the 'level' menu.
In the same menu, you can disable the use of voting/ranking; if you switch it off, it will also be removed from the list.

You can also disable the use of categories in the general settings (under System -> Global configuration -> J!TrackGallery ).

Hope this helps. Let me know in case you find something that does not work.

Best regards, Marco.

**Comment by mastervanleeuwen** [comment]
Hi Marco,

In the previous version, the 'category' and 'level' selections were still shown in the filter box in the overview map and the track list. I found a way to disable this as well in the latest release candidate:

https://github.com/mastervanleeuwen/J-TrackGallery/releases/tag/0.9.34-rc32

Could you try this one out and let me know whether it works for you?

Best regards, Marco.
