### ISSUE TITLE
bug : estimez votre temps de parcours

### ISSUE THREAD

**Issue by perlim-pinpin** [mastervanleeuwen/J-TrackGallery#42]
Hi Marco

ce qui est entouré en bleu ne fonctionne pas

![Screenshot 2023-01-18 at 15-59-44 2023-01-15 -- perlimpinpin](https://user-images.githubusercontent.com/122956429/213206192-575334af-1878-4484-bffe-dabc0c409a03.png)

thank you
best regards

**Comment by mastervanleeuwen** [comment]
Hi,

Thanks for your message. This is fixed in the new version posted here: https://github.com/mastervanleeuwen/J-TrackGallery/releases/tag/0.9.34-rc26

Best regards, Marco.
