### ISSUE TITLE
paramétrer "informations sur cette trace GPS" 

### ISSUE THREAD

**Issue by perlim-pinpin** [mastervanleeuwen/J-TrackGallery#43]
Hi Marco 

est-il possible de paramétrer les flèches bleues ?
C'est à dire pouvoir afficher, ou pas, chaque information.
par exemple, si je ne veux pas afficher "téléversé par pinpin", pouvoir décocher une case pour que ça ne s'affiche pas.
Et même, pouvoir changer le titre.

![Screenshot 2023-01-18 at 15-59-44 2023-01-15 -- perlimpinpin](https://user-images.githubusercontent.com/122956429/213207832-8a9e7da6-b08a-4891-9dce-b4331e81f264.png)

thank you
best regards

**Comment by mastervanleeuwen** [comment]
Bonjour,

Merci pour les suggestions. C'est possible dans le nouveau version ici: 
https://github.com/mastervanleeuwen/J-TrackGallery/releases/tag/0.9.34-rc30

(le link 'Share' est toujours la, may c'est facile de parametriser ca aussi)

Cordialement, Marco.
