### ISSUE TITLE
Suppression en frontale

### ISSUE THREAD

**Issue by 71150** [mastervanleeuwen/J-TrackGallery#48]
Bonjour Marco
Tout d'abord félicitations pour votre application que je vais mettre en place auprès de mon association de randonnée.
Actuellement je ne rencontre qu'un seul petit problème c'est l'impossibilité de supprimer une trace depuis le frontal. Ca fonctionne en backend. J'ai votre version rc 26. Dans de précédentes version tout était ok.
Cordialement

**Comment by mastervanleeuwen** [comment]
Bonjour,

Merci pour le rapport. J'ai résolu le problème et publié une nouvelle version : https://github.com/mastervanleeuwen/J-TrackGallery/releases/tag/0.9.34-rc28

Cordialement, Marco.

**Comment by 71150** [comment]
Bonjour Marco

C'est parfait, ça fonctionne, bravo. Je ne comprends pas pourquoi il y a deux boutons annuler lorsque l'on se trouve en frontale en mode ajouter une trace. 
![ajout-bouton-annuler](https://user-images.githubusercontent.com/123870784/215993398-936cb565-39fc-4cfe-b589-b9ccac65e6ce.JPG)

**Comment by mastervanleeuwen** [comment]
Bonjour,

Je pense que c'est un probleme de traduction. Un des deux boutons est pour reinitialiser le formulaire, et l'autre est pour completement supprimer le trace. Je peux changer le bouton en milieu a 'Reinitialiser' Est-ce ca est clair, ou peut-etre il y a une meilleur formulation?

Cordialement, Marco.

**Comment by 71150** [comment]
Bonjour

C'est parfaitement compréhensible. Merci pour votre travail
Cordialement
