### ISSUE TITLE
Disable terrains description

### ISSUE THREAD

**Issue by noelada** [mastervanleeuwen/J-TrackGallery#49]
Hi Marco,
When we select **My Maps** from the overview screen, there is a terrain column displaying when terrain descriptions have been disabled. Also giving a percentage for map height in Maps configuration does not seem to work.
Regards,
Noel.

**Comment by mastervanleeuwen** [comment]
Dear Noel,

Thanks for the report. The issue with the terrain descriptions in the 'My Tracks' view is fixed in this release:
https://github.com/mastervanleeuwen/J-TrackGallery/releases/tag/0.9.34-rc29

Concerning the issue with giving a percentage for the map height, I am less sure. This would only work when the map is placed inside a container with a fixed height. Is that the case in your usage? Are you using the plugin in this case?

Best regards, Marco.

**Comment by noelada** [comment]
Thanks Marco,We do not need the percentage option. Perhaps you could edit the help text so it does not appear as an option?.The “Minimum ascent elevation filter” in basic configuration is set to 10 as default, but does not seem to work. We have tracks with crazy negative elevation points such as <ele>-20000</ele> . This results in crazy total ascent and descent values in GPS Track Details and large negative spikes in the elevation profile. It would be preferable if negative elevations could be removed from any uploaded gpx file.I have modified jtrackgallery_maps.php line 162 to allow the link title (GPX track) to be in plugin translations. We have then used an override translation to change “GPX text” to “Click for elevation profile and GPX downloads” which is more informative for our users. Perhaps you could make this change also in a future release so users can alter the link name.?I have also modified form.php to add to the track description the script required to display the map ( if the script is not already there). The script builds the gpx file name from $this->track->file so it is accurate. The script is generated when uploading a new track or editing a track. To stop the script being executed by Jtrack, I have added an asterisk before the last }. Our users need to remove the asterisk when they copy the description to the place where they want the map to be displayed. Perhaps something like this could be a configuration option ?Sorry this reply is so long.We love the extension.Regards,Noel.P.S. An example of what is generated is {JTRACKGALLERYMAP} gpxfilename=anakiegorgewalk.gpx, show_link=1 {/JTRACKGALLERYMAP*} . Sent from my iPadOn 8 Apr 2023, at 6:59 am, Marco van Leeuwen ***@***.***> wrote:﻿
Dear Noel,
Thanks for the report. The issue with the terrain descriptions in the 'My Tracks' view is fixed in this release:
https://github.com/mastervanleeuwen/J-TrackGallery/releases/tag/0.9.34-rc29
Concerning the issue with giving a percentage for the map height, I am less sure. This would only work when the map is placed inside a container with a fixed height. Is that the case in your usage? Are you using the plugin in this case?
Best regards, Marco.

**Comment by noelada** [comment]
Hi Marco,

Most modules in jtrack use the System Configuration - default editor, however components – com_jtg – views – track – tmpl – form.php is hard coded to use tinymce. Is it possible to use the default editor instead? I have made this change and it seems to work OK. Our default editor is JCE and it confuses our users to have tinymce for track descriptions.

Regards,

Noel.

**Comment by mastervanleeuwen** [comment]
Dear Noel,

Glad to hear that J!Trackgallery is working for you! 

The choice of editor for the track description was not intentional; I have adapted the code to use the site-wide default as you suggested, in this version:
https://github.com/mastervanleeuwen/J-TrackGallery/releases/tag/0.9.34-rc30

I also added the possibility to choose which fields are shown in the 'GPS info' section, and added the possibility to show total time (duration) and average speed. For now, this only works in the standard track view, but I am planning to also make this configurable in the plugin.

Best regards,

Marco.

**Comment by noelada** [comment]
Thanks Marco,

Cheers,

Noel.

**Comment by noelada** [comment]
Hi Marco,

I have made a change to jtrackgallery_maps.php to enable us to change the hard coded GPX link name. Could you please make the same or similar change to the plugin as a template plugin content override does not work. The change I made is at around line 162

 

$plg_html .= '<div class="jtg-gpx-link"><a href="'.JRoute::_('index.php?option=com_jtg&view=track&id='.$plg_call_params['id']).'"'.$target. '>'. JText::_ ( 'PLG_JTG_MAPS_LINK_NAME' ).'</a></div>';

 

We have used a language override PLG_JTG_MAPS_LINK_NAME="Click for <b>elevation profile</b> and GPX downloads" to change the hard coded wording, but you could make the default the same as the hard coded wording.

Great work on the extension. Our members love it.

Regards,

Noel.

**Comment by mastervanleeuwen** [comment]
Hi Noel,

I implemented a way to customise the text of the link to the track using the plugin settings:
<img width="982" alt="image" src="https://user-images.githubusercontent.com/23643853/236629647-c6c268fd-4fb3-4fc7-bf5b-c26ddb82e24d.png">

in the new version here: https://github.com/mastervanleeuwen/J-TrackGallery/releases/tag/0.9.34-rc31

Please let me know whether this works for you.

Best regards, Marco.

**Comment by noelada** [comment]
Thanks Marco,

There is a typo on line 302. $plgParam should be $plgParams

Regards,

Noel.

**Comment by mastervanleeuwen** [comment]
Thanks for the report. This typos is fixed in the new release candidate: 

https://github.com/mastervanleeuwen/J-TrackGallery/releases/tag/0.9.34-rc32
