### ISSUE TITLE
I can't create a new terrain

### ISSUE THREAD

**Issue by camminateinfriuli** [mastervanleeuwen/J-TrackGallery#50]
I can't create a new terrain when I save it gives me this error even if it also says that it has been saved it is not saved.
![new-terrain-save-error](https://user-images.githubusercontent.com/68971180/228893453-c696cb57-d6e3-416a-bfbd-372cd2548399.png)

**Comment by mastervanleeuwen** [comment]
Thanks for the report. This was due to a problem in the data base definition. I have implemented a fix in this version:

https://github.com/mastervanleeuwen/J-TrackGallery/releases/tag/0.9.34-rc29

Could you try it and let me know in case it does not work?

Best regards, Marco.

**Comment by camminateinfriuli** [comment]
This works I can insert new terrains.
But this release removes some features from the last release, when will you bring the various fixes back to the stable release?

**Comment by mastervanleeuwen** [comment]
Thanks for the positive feedback.

I did not intend to move any features; it may be an unintentional side effect, or some problem with a recent commit. Could you give an example of something that worked before but not anymore, to help identify what may have happened?

**Comment by camminateinfriuli** [comment]
Then one of the things is surely that the category icon is missing in the track list.

![jtg1](https://user-images.githubusercontent.com/68971180/233182840-62c19045-648b-44e1-bb4e-51fb9e1b9dcf.png)
![jtg2](https://user-images.githubusercontent.com/68971180/233182836-6c6aa55a-9f4a-43cf-b507-0a495eb7f989.png)

**Comment by mastervanleeuwen** [comment]
I see, this is something that is now configurable. It should be on by default, but something may have gone wrong in the update process. Could you check under the 'Global configuration' settings in the J!TrackGallery tab, whether it is on:

<img width="1092" alt="image" src="https://user-images.githubusercontent.com/23643853/233208187-54076b27-74d3-4307-8bcd-820115c71022.png">

Even if it is on, please make sure to save the settings once to update the settings in the database. Let me know whether that fixes the problem; I may be able to improve this for other users.

**Comment by camminateinfriuli** [comment]
Thanks, it works perfectly, sorry. In fact it was already on view (YES) so I put it on NO and saved, then I put it back on YES and they came back.

**Comment by camminateinfriuli** [comment]
> Thanks for the report. This was due to a problem in the data base definition. I have implemented a fix in this version:
> 
> https://github.com/mastervanleeuwen/J-TrackGallery/releases/tag/0.9.34-rc29
> 
> Could you try it and let me know in case it does not work?
> 
> Best regards, Marco.

It still doesn't work for me, it gives me the same error, probably when I tried I was wrong

**Comment by mastervanleeuwen** [comment]
Thanks for the report. This took some time to identify because the error only occurs on Joomla 4, and not on Joomla 3 where I do most of my testing. Is should be fixed in this version:

https://github.com/mastervanleeuwen/J-TrackGallery/releases/tag/0.9.34-rc32

Could you try it and let me know whether it works now?

**Comment by camminateinfriuli** [comment]
Yes this works perfectly.

Thank you
