### ISSUE TITLE
more levels

### ISSUE THREAD

**Issue by camminateinfriuli** [mastervanleeuwen/J-TrackGallery#51]
To adapt it to my site I added difficulty levels.

![image](https://user-images.githubusercontent.com/68971180/232478595-0c5de3b0-4c62-440e-8ae4-1719b12e5f60.png)

Apart from the fact that in the scale it still writes me 7/5 and not 7/8, but this is not a big problem.

![image](https://user-images.githubusercontent.com/68971180/232479936-697808d4-5876-4752-b1e8-a0e1382a3ff1.png)

The thing that causes me problems is that if I open the track filter, it only displays the old standard level search parameters

**Comment by camminateinfriuli** [comment]
Thank you for the wonderful work you are doing, I await the resolution of this problem to be able to put the J!TrackGallery package in the production site

Thanks Gianni

**Comment by mastervanleeuwen** [comment]
Dear Gianni,

This was a bit more involved than I expected, but it should work in the new version posted here: https://github.com/mastervanleeuwen/J-TrackGallery/releases/tag/0.9.34-rc31

Please try it out and let me know in case you spot any problems.

Best regards, Marco.

**Comment by camminateinfriuli** [comment]
> Dear Gianni,
> 
> This was a bit more involved than I expected, but it should work in the new version posted here: https://github.com/mastervanleeuwen/J-TrackGallery/releases/tag/0.9.34-rc31
> 
> Please try it out and let me know in case you spot any problems.
> 
> Best regards, Marco.

Thank you so much wonderful work.

I don't know how to thank you and I respect you for the punctual and precise work you do.

Thank you
