### ISSUE TITLE
more than one category

### ISSUE THREAD

**Issue by camminateinfriuli** [mastervanleeuwen/J-TrackGallery#52]
If multiple categories are selected in a track, and it is allowed, when viewing the track from these errors.

Warning: Undefined array key "12,15,20,22" in /var/www/vhosts/camminateinfriuli.it/httpdocs/components/com_jtg/views/track/tmpl/default.php on line 158

Warning: Attempt to read property "usepace" on null in /var/www/vhosts/camminateinfriuli.it/httpdocs/components/com_jtg/views/track/tmpl/default.php on line 158

**Comment by mastervanleeuwen** [comment]
Thanks for the report. This was indeed a bug, which is fixed in this release:

https://github.com/mastervanleeuwen/J-TrackGallery/releases/tag/0.9.34-rc30
