### ISSUE TITLE
Bug/typo in com_jtg/helpers/gpsClass.php

### ISSUE THREAD

**Issue by noelada** [mastervanleeuwen/J-TrackGallery#59]
Hi Marco,
Line 193 causes an error if a route is in the GPX file being added. The line should read:
$npt = count($this->route[$nrt-1]->coords);

Cheers,
Noel.
PS: I have fixed this in our site so not urgent.

**Comment by mastervanleeuwen** [comment]
Hi Noel, 

Thanks for localising the bug. I have included the fix in the latest pre-release: 

https://github.com/mastervanleeuwen/J-TrackGallery/releases/tag/0.9.34-rc34

Best regards, Marco.
