### ISSUE TITLE
Error if gpx filename is too long

### ISSUE THREAD

**Issue by jvevfvf** [mastervanleeuwen/J-TrackGallery#61]
I'm getting a database error if the gpx filename is longer than the db field length.
I've put in a hack of sorts into saveFile and updateFile in models/track.php to just truncate the filename.
(just before the call to JtgHelper::createimageandthumbs)

                                 $name = JFile::stripExt($imgfilename);
                                if (strlen($name)>45)
                                {
                                    $name=substr($name,0,45);
                                }
                                $imgfilename=$name.".".$ext;
Cheers
Jeff

**Comment by mastervanleeuwen** [comment]
Hi Jeff,

Thanks for the report and for the suggested fix. 

I had already increased the maximum length of the file name to 127 characters a while ago, so if you have upgraded to a recent version, it should already allow much more than 45 characters. That said, the code was failing 'silently' when the file name is longer, so I implemented the suggested truncation and have updated some of code and warning messages to correctly reflect the limit in this commit:
https://github.com/mastervanleeuwen/J-TrackGallery/commit/4656715b589ef7436165f786c6b1f3c6f7dba2d6

This will be included in the next release.

Best regards, Marco.
