### ISSUE TITLE
? bug in recent change to maphelper.php

### ISSUE THREAD

**Issue by noelada** [mastervanleeuwen/J-TrackGallery#62]
Hi Marco,
After the latest update, I am getting errors from com_jtg/helpers/maphelper.php
The error is that $row->icon_e and $row->icon_n do not exist. If I change **icon** to **start** it gets rid of the errors.
The line numbers are 250 and 251 in maphelper.
Best wishes,
Noel.

**Comment by mastervanleeuwen** [comment]
Hi Noel,

Thanks for the report. This was due an incomplete commit. The new version here: 
https://github.com/mastervanleeuwen/J-TrackGallery/releases/tag/0.9.34-rc35
adds these fields to the data base, to allow drawing the track marker in a different position in the overview map for some specific use cases.

Best regards, Marco.

**Comment by noelada** [comment]
Hi Marco,

I am getting an installation error with com_jtg.zip in this release:

Warning

JInstaller: :Install: Error SQL You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'start_n, ADD `icon_e` FLOAT(20) NOT NULL DEFAULT start_e' at line 2

 

Regards,

Noel.

**Comment by noelada** [comment]
Hi Marco,

I think the installation error was caused by the localhost environment I was using. I tried installing on our test server and it was successful. Please ignore my previous email.

Regards,

Noel.
