### ISSUE TITLE
Color of the track

### ISSUE THREAD

**Issue by Bredouard** [mastervanleeuwen/J-TrackGallery#64]
Hi,

is it possible to change the color of the track and to add KM-Points?

cu

Eddy

![Screenshot Auto-pédestre Beaufort](https://github.com/mastervanleeuwen/J-TrackGallery/assets/95382920/aba59f71-4622-41ea-a7f6-28df5328ce54)

**Comment by mastervanleeuwen** [comment]
Hi Eddy,

I have added the possibility to set the line color and add distance markers in this version:
https://github.com/mastervanleeuwen/J-TrackGallery/releases/tag/0.9.34-rc39
Please give it a try and let me know. 

NB: Make sure to visit the **configuration menu and save the changes** (even if you did not change anything) one time to make sure that the new settings are properly picked up.

Best regards, Marco.
