### ISSUE TITLE
Tracks color in "Traces in the Overview"

### ISSUE THREAD

**Issue by Bredouard** [mastervanleeuwen/J-TrackGallery#66]
Hi Marco,

Would it be possible to display all tracks 

in "Traces in the Overview" in the same color or in different colors depending on the category?

I think that would make the whole map clearer and less restless due to the many colors.

Eddy
Site under construction: http://autopedestres.wwl.lu/AP/index.php

![Screenshot 2023-09-07 at 18-59-27 Auto-pédestres aus 5 Regiounen](https://github.com/mastervanleeuwen/J-TrackGallery/assets/95382920/52525255-3796-4970-9448-09d096f27d99)

**Comment by mastervanleeuwen** [comment]
Hi Eddy,

Thanks for the suggestion. In the latest development version, the track colors are configurable; by default there are four different colors that the code cycles through for the tracks. You can choose to make all four colors the same, or go with 2 different colors by setting them pairwise. Hope this helps. The settings in the global configuration:
<img width="771" alt="image" src="https://github.com/mastervanleeuwen/J-TrackGallery/assets/23643853/33060448-fb44-4961-9a08-4767daa7cf0c">

This is available in the latest release:
https://github.com/mastervanleeuwen/J-TrackGallery/releases/tag/0.9.35
but I suggest to switch to the latest pre-release: 
https://github.com/mastervanleeuwen/J-TrackGallery/releases/tag/0.9.35-d

Best regards, Marco.
