### ISSUE TITLE
Category page 

### ISSUE THREAD

**Issue by Bredouard** [mastervanleeuwen/J-TrackGallery#68]
Hello Marco,

Would it be possible to switch off the search function on the category page 

and instead of the last tracks, show all the tracks in this category in alphabetical order, 

without the arrow at the beginning and without the category name at the end, all this for a better display on the mobile phone?

Eddy
Site under construction: http://autopedestres.wwl.lu/AP/index.php

![Screenshot 2023-09-07 at 19-27-34 Auto-pédestres Regioun Éislek](https://github.com/mastervanleeuwen/J-TrackGallery/assets/95382920/1cd963ef-d29e-4292-8cd6-5a888350d4f9)

**Comment by mastervanleeuwen** [comment]
Hi Eddy,

Thanks for the suggestion. Are you also using the main overview page with all tracks, or only the category views? The two views share the same code, so if I add a setting to make the filter-box switchable, it would also disappear from the main overview page. Making this more controllable is of course possible, but slightly more complex.

For the track list, you could remove the 'Latest tracks' by setting the number to 0 in the configuration:
<img width="581" alt="image" src="https://github.com/mastervanleeuwen/J-TrackGallery/assets/23643853/2d92e23d-0849-471c-b2b9-567c07567582">
This will produce a 'cleaner' page, but adding the full list is also a good idea.

Best regards,

Marco.

**Comment by Bredouard** [comment]
Hi Marco,
many thanks for your answer.

Yes, I use both, the main overview and category views.

My pages are static pages where no tracks are added anymore so it would make more sense to display the tracks alphabetically.

Here is the link to my current page: [https://auto-pedestres.lu/index.php/auto-pedestres-no-regiounen/ap-regioun-mellerdall](https://auto-pedestres.lu/index.php/auto-pedestres-no-regiounen/ap-regioun-mellerdall), which I would like to replace with J-TrackGallery because your the display looks better ;-)

cu

Eddy

**Comment by mastervanleeuwen** [comment]
The 'category view' is implemented in the new pre-release: https://github.com/mastervanleeuwen/J-TrackGallery/releases/tag/0.9.34-rc44
