### ISSUE TITLE
Link colors

### ISSUE THREAD

**Issue by Bredouard** [mastervanleeuwen/J-TrackGallery#69]
Hi Marco,

where or how can I change the link colors?

Eddy
Site under construction: http://autopedestres.wwl.lu/AP/index.php

**Comment by mastervanleeuwen** [comment]
Hi Eddy,

The link text color for the links in the 'latest tracks' is set in the template style file com_jtg/assets/template/default/jtg_style.css

in these lines:
`.toptracks_1_entry ul a,.toptracks_1_title ul a,.toptracks_2_entry ul a,.toptracks_2_title ul a,.toptracks_3_entry ul a,.toptracks_3_title ul a,.toptracks_4_entry ul a,.toptracks_4_title ul a
	{ /* BoxEntry Link */
	color: #555555;
}`

to change it, you could consider making your own style settings by making a new directory in com_jtg/assets/template with a name that you choose for the style. You can copy all the files from the default style and then edit them. Your style should then appear as a choice in the settings menu:
<img width="1127" alt="image" src="https://github.com/mastervanleeuwen/J-TrackGallery/assets/23643853/aae19ee6-278f-4e37-bb34-76eabf28a413">

This way, the style will not be overwritten when you install new versions of J!TrackGallery.

Best regards, Marco.

**Comment by Bredouard** [comment]
Hi Marco,

Thanx it works.
