### ISSUE TITLE
Map menus > Category language string no text

### ISSUE THREAD

**Issue by joomleb** [mastervanleeuwen/J-TrackGallery#7]
Hi guys,
PHP 7.4.20 + Joomla 3.9.27 + j-TrackGallery 0.9.32 RC2

- Deafult View with Map - menu item type
- Overview Map - menu item type

Into the Category drop down menu the Category languages strings are shown instead of the Text, Am I right ? - I add an image for you
![jTrack-Map-menus-Categories](https://user-images.githubusercontent.com/14607633/123867095-8716c100-d8f3-11eb-97ff-42ed8536a4f3.jpg)

**Comment by mastervanleeuwen** [comment]
Thanks for the report. This has now been fixed by duplicating the necessary language strings in commit https://github.com/mastervanleeuwen/J-TrackGallery/commit/ae3d9ed57b21b5bd005aebd61e0935282f1a6c27
