### ISSUE TITLE
Error message GPX download when using J!TrackGallery Comments

### ISSUE THREAD

**Issue by Bredouard** [mastervanleeuwen/J-TrackGallery#70]
Hi Marco,

When I activate J!TrackGallery Comments, 

the GPX download no longer works and an error message is displayed.

Without Commenting system it works perfect

Eddy
Site under construction: http://autopedestres.wwl.lu/AP/index.php

![Screenshot 2023-09-07 at 19-35-16 Auto-pédestre Schieren _ Schieren - 8 km - Auto-pédestres aus ganz Lëtzebuerg](https://github.com/mastervanleeuwen/J-TrackGallery/assets/95382920/40b73d2a-e417-4dd9-954a-845469d641ad)
![Capture d'écran 2023-09-07 194055](https://github.com/mastervanleeuwen/J-TrackGallery/assets/95382920/98d2d460-ea3a-4096-8b62-2812cb594365)

**Comment by mastervanleeuwen** [comment]
Hi Eddy,

Thanks for the report, this bug should be fixed in the new pre-release:
https://github.com/mastervanleeuwen/J-TrackGallery/releases/tag/0.9.34-rc41

Best regards, Marco.

**Comment by Bredouard** [comment]
Hi Marco,
The GPX download works now, 
but I can't fill out the "Comment text*" field in the comment form.
Best regards,
Eddy

**Comment by mastervanleeuwen** [comment]
Hi Eddy,

Hmm, that is strange; it was working on my test site:
<img width="948" alt="image" src="https://github.com/mastervanleeuwen/J-TrackGallery/assets/23643853/b7ecf405-c912-4a03-a818-934733c249cb">

Is there any error message in the browser? The comment editor uses JavaScript, maybe that causes a problem; could you open the 'developer tools' in your browser to see whether there is JavaScript error in the console window on the lower right?

Best regards, Marco.

**Comment by Bredouard** [comment]
Hi Marco, Thanx for your answer.

I can't find any error message ;-((

Here's the link to a comment page: http://autopedestres.wwl.lu/AP/index.php/de/auto-pedestres-aus-5-regiounen/auto-pedestres-regioun-eislek/track/58

Best regards,

Eddy

**Comment by mastervanleeuwen** [comment]
Hi Eddy,

I see; this may have something to do with your editor settings. Could you check which editor you have selected in the system/general settings:
<img width="775" alt="image" src="https://github.com/mastervanleeuwen/J-TrackGallery/assets/23643853/df17493d-a759-48c3-aaa9-9a3231c300b5">
I have tinyMCE. Looking at the code of your website, it looks like it is trying to use an editor that goes by the name 'wf'
```
<div class="editor wf-editor-container mb-2 joomla4"><div class="wf-editor-header"></div><textarea spellcheck="false" autocomplete="off" name="text" id="text" cols="80" rows="8" style="width: 100%; height: 200px; display: none;" class="mce_editable wf-editor" aria-hidden="true"></textarea><div role="application" aria-labelledby="text_voice" id="text_parent" class="mceEditor mceDefaultSkin" style="display: block;"><span class="mceVoiceLabel" style="display:none;" id="text_voice">Rich Text Area</span><div role="presentation" id="text_tbl" class="mceLayout"><div class="mceIframeContainer"><iframe id="text_ifr" frameborder="0" allowtransparency="true" title="Rich Text Area" style="height: 180px;" src="javascript:&quot;&quot;"></iframe></div></div></div>
</div>
```
which for some reason does not seem to work. Are you using a specific plugin/addon to provide this editor?

Best regards, Marco.

**Comment by Bredouard** [comment]
Hi Marco,

I usually use the JCE editor.

I have now switched to TinyMCE and now it works ;-))

cu

Eddy
