### ISSUE TITLE
Error message when trying to upgrade to version 0.9.34-rc41

### ISSUE THREAD

**Issue by sergpnm** [mastervanleeuwen/J-TrackGallery#71]
Hi Marco,
When I try to upgrade to version 0.9.34-rc41 I get an error message:

----
JInstaller: :Install: Ошибка SQL: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'IF NOT EXISTS `icon_n` FLOAT(20), ADD IF NOT EXISTS `icon_e` FLOAT(20)' at line 2
Расширение: Обновление: Не удалось выполнить SQL-запрос: Ошибка базы данных с номером 1064.
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'IF NOT EXISTS `icon_n` FLOAT(20), ADD IF NOT EXISTS `icon_e` FLOAT(20)' at line 2
SQL =
ALTER TABLE `#__jtg_files`
ADD IF NOT EXISTS `icon_n` FLOAT(20),
ADD IF NOT EXISTS `icon_e` FLOAT(20);
---

Is there any way to fix this?

Best regards, Sergey.

**Comment by mastervanleeuwen** [comment]
Hi Sergey,

It seems like the data base engine of your website does not recognise the 'if not exists' condition. To confirm this, could you let me know which data base engine you are using? You can find this information in the administrator menus under 'System' and then 'Global configuration' and then under 'Database':
<img width="747" alt="image" src="https://github.com/mastervanleeuwen/J-TrackGallery/assets/23643853/eb107082-3b6c-4e80-826a-2b6b43081699">

Best regards, Marco.

**Comment by mastervanleeuwen** [comment]
Hi Sergey, all,

I see; it turns out that some of the SQL commands that were used in the upgrade script only work on MariaDB. I have removed the offending commands in this new version:

https://github.com/mastervanleeuwen/J-TrackGallery/releases/tag/0.9.34-rc42

Could you try this one and let me know whether it works?

Best regards, Marco.

**Comment by 71150** [comment]
Bonjour

Je viens d'installer la version rc42 aucun problème d'installation. Merci beaucoup pour votre travail
