### ISSUE TITLE
“Previous” and “Next” buttons to the category view

### ISSUE THREAD

**Issue by Bredouard** [mastervanleeuwen/J-TrackGallery#72]
Hi Marco,

It's me again ;-)

Would it be possible to add “Previous” and “Next” buttons to the category view?

This would allow for easier and faster browsing of each category.

Best regards,

Eddy

PS: Thank you for the good job . . . 

![image](https://github.com/mastervanleeuwen/J-TrackGallery/assets/95382920/2954b700-2ae0-47fe-94cd-10089d011d8c)

**Comment by mastervanleeuwen** [comment]
Hi Eddy,

Thanks for the suggestions and requests. I have now added a separate 'Category view' which can show a overview map and/or a track list (to be configured in the global configuration menu) and has buttons for the next and previous category. You can see it in action on my test page:
https://jtrackgalleryj4.gta-trek.eu/index.php/en/trekking/cat/12

This version also allows to remove the track filter/search box in the overview page and/or in the track listing page.

The new version with this included is available here: https://github.com/mastervanleeuwen/J-TrackGallery/releases/tag/0.9.34-rc44

Please give it a spin and let me know whether this works for you.

Best regards, Marco.

**Comment by Bredouard** [comment]
Am Do., 4. Jan. 2024 um 21:12 Uhr schrieb Marco van Leeuwen <
***@***.***>:

**Comment by Bredouard** [comment]
Hi Marco,

Since my current program is already causing me a lot of problems and
is no longer updated,
I decided on another tool that is already ready and can be used almost
immediately.

BUT I THANK YOU SO MUCH for the work you have done and wish you
continued success.

Best regards,

Eddy


Am Sa., 6. Jan. 2024 um 19:50 Uhr schrieb Eddy Brix ***@***.***>:

**Comment by mastervanleeuwen** [comment]
Thanks Eddy!
