### ISSUE TITLE
Use plugin in Joomla 3.x not succesful :-(

### ISSUE THREAD

**Issue by Ronald1947** [mastervanleeuwen/J-TrackGallery#74]
Hello
I'm trying to implant the plugin on my website www.remdewaal.nl. However, that does not work. Or the plugin is not recognized. Or I get the error message: Call to undefined method JtgHelper::p arseTrackInfo()
I have tried several options:
{jtrackgallerymap} law7-1_amsterdam-aalsmeer.gpx, show_link=1 {/jtrackgallerymap}
{jtrackgallerymap} id=18_link=1 {/jtrackgallerymap}
{gallery} law7-1_amsterdam-aalsmeer.gpx, show_link=1 {/gallery}
What am I doing wrong?
With kind regards,
Ronald

**Comment by mastervanleeuwen** [comment]
Hello Ronald,

This error points to an incompatibility between the versions of the component (com_jtg.zip) and the plugin. Could you try to update/install a recent version of both, e.g. from here:

https://github.com/mastervanleeuwen/J-TrackGallery/releases/tag/0.9.34-rc41

Best regards, Marco.

**Comment by Ronald1947** [comment]
**TOP** Marco,
Thanks!
With kind regards,
Ronald
