### ISSUE TITLE
Max items in one article

### ISSUE THREAD

**Issue by Ronald1947** [mastervanleeuwen/J-TrackGallery#75]
Hi,

Where can I change the max plugins in one article? 
In this article there are 10 tracks but J-TrackGallery excepts only 9 items.
https://www.remdewaal.nl/wandelen/law/12-wandelen/law/63-route-pieterpad-deel-1
With kind regars,
Ronald

**Comment by mastervanleeuwen** [comment]
Hi,

This limit is hardcoded; mostly to avoid producing very large/heavy web pages. I have increased it to 50 in this release:
https://github.com/mastervanleeuwen/J-TrackGallery/releases/tag/0.9.34-rc43
Please give it a try and let me know if that works for you.

Btw: I see that your trails are parts of long distance trails. You use configure a category for each long distance trail, and use that to generate overview maps for each long distance trail, by showing a 'category map'.

Best regards, Marco.

**Comment by Ronald1947** [comment]
Hi Marco,

**Perfect!**
https://www.remdewaal.nl/wandelen/law/12-wandelen/law/63-route-pieterpad-deel-1
https://www.remdewaal.nl/wandelen/law/12-wandelen/law/64-routes-pieterpad-deel-2
Thanks for your very quick answer!
With kind regards,
Ronald
