### ISSUE TITLE
Trackgallery recent tracks

### ISSUE THREAD

**Issue by stay4you** [mastervanleeuwen/J-TrackGallery#76]
Hi
Just wondering if their would be any way to define a location via the Trackgallery recent tracks module adding longitude and latitude to show a map of a location.

  Thanks 
        Gary

**Comment by mastervanleeuwen** [comment]
Hi Gary,

Thanks for this suggestion; before making any changes, I would like to understand a little bit better what you would like to achieve.

One possibility is to use the 'overview map' view, where you can define an specific area to show, see the example on my test page:
https://testing.gta-trek.eu/index.php/nl/valroc-overview
However, as you may have noticed, the 'recent tracks' and 'most popular tracks' are not restricted to the same region. Is that what you are asking for?

I have also just added a new 'category view', which may also be useful for your purpose; to use this, you could define categories based on geographical areas and then use the category view to show a map and a list of tracks that are in given area. An example page is available here: https://jtrackgalleryj4.gta-trek.eu/index.php/en/trekking/cat/12 (in this example, the category is a type of activity; not a geographical area; you can define categories yourself to suit your needs)

Please let me know if any of the above would work for you, or if you have something different in mind.

Best regards, Marco.

**Comment by stay4you** [comment]
Hi sorry for the delay responding I have been trying different setups, the main reason for the module is for seo content for the location. I have tried using a custom module linked to the overview map to add content but am not happy with the result.
Regards
   Gary

**Comment by mastervanleeuwen** [comment]
Hi Gary,

Could you describe in a bit more detail what you want to achieve? The overview map page has the possibility to define the center point of the map, to define an area for which the tracks are shown on the map. Would you like to restrict the track list to a sub-area as well?

I looked on your website, and noticed that you have been using the 'geo' view, which is a bit buggy. If you use the default overview map view, you can achieve something [like this](https://www.stay4you.com/guide/tracks-routes/scottish-tracks-map/jtg?lon=-3.3&lat=57.3&map_zoom=6). I noticed that the zoom levels are somehow not ideal for this exact page; it seems that the ideal zoom level is between 6 and 7.

Let me know if this goes in the right direction, or whether you have something else in mind.
 
Best regards, Marco.

**Comment by mastervanleeuwen** [comment]
Hi Gary,

I have added a module that lists tracks near a given location. The location is specified by giving a latitude and longitude in decimal format. Hope this is what you had in mind. I am not so familiar with modules, but it looks like you can have multiple instances of the module with different locations.

The new module can be found here: https://github.com/mastervanleeuwen/J-TrackGallery/releases/download/0.9.35-d/mod_jtrackgallery_closest.zip

Best regards, Marco.

**Comment by stay4you** [comment]
Hi Marco
That's great, thank you so much for the module, a great addition to the package.
Regards
   Gary
