### ISSUE TITLE
Error in gpsClass  Deprecated: str_replace()  and  jtg.php Deprecated: strlen()

### ISSUE THREAD

**Issue by camminateinfriuli** [mastervanleeuwen/J-TrackGallery#77]
**Error in gpsClass:**
Deprecated: str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated 
/var/www/vhosts/........./httpdocs/components/com_jtg/helpers/gpsClass.php on line 1458

Deprecated: str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated 
/var/www/vhosts/........./httpdocs/components/com_jtg/helpers/gpsClass.php on line 1459

Deprecated: str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated 
/var/www/vhosts/........./httpdocs/components/com_jtg/helpers/gpsClass.php on line 1460

**Original**

1458  $name = trim(str_replace($replace, $with, $wp->name));
1459  $cmt = trim(str_replace($replace, $with, $wp->cmt));
1460  $desc = trim(str_replace($replace, $with, $wp->desc));
1461  $ele = (float) $wp->ele;

**Modify in**

1458  $name = trim($name ? str_replace($replace, $with,$wp->name): "");
1459  $cmt = trim($cmt ? str_replace($replace, $with, $wp->cmt): "");
1460  $desc = trim($desc ? str_replace($replace, $with, $wp->desc): "");
1461  $ele = (float) $wp->ele;

**Original**

1472  public function parseWPs()
1473	 {
1474	 	 if ( empty($this->wps))
1475		 {
1476			 return false;
1477		 }

**Modify in**

1472	public function parseWPs()
1473	{
1474			$name= "";
1475			$cmt ="";
1476			$desc="";
1477		if ( empty($this->wps))
1478		{
1479			return false;
1480		}

**Error in jtg.php:**

Deprecated: strlen(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/vhosts/......../httpdocs/components/com_jtg/jtg.php on line 84

83  $classname = 'JtgController';
84  if (strlen($controller)) $classname .= ucfirst($controller);           ORIGINAL  
**modify in**
84  if (strlen($controller ?? '')) $classname .= ucfirst($controller);	//     SOLUTION
85  $controller = new $classname;

This is my solution.

**Comment by mastervanleeuwen** [comment]
Thanks for the report and the suggested fixes. I have implemented them (with minor changes) in this fixup release: https://github.com/mastervanleeuwen/J-TrackGallery/releases/tag/0.9.35-fixup
