### ISSUE TITLE
Terrains and Categories not showing all selected options

### ISSUE THREAD

**Issue by Wesmaster** [mastervanleeuwen/J-TrackGallery#78]
Terrains and Categories not showing all selected options in the following views:
* files
* user

In the track overview itself it is working but that is due to it using a different helper method of making the list.

**Comment by Wesmaster** [comment]
This is happening when routes are made/edited through the frontend. If the route is edited through the backend, the values show correct in the frontend.

**Comment by mastervanleeuwen** [comment]
Thanks for the detailed report. There was a bug in parsing multiple terrains in the frontend, which is fixed in this release:

https://github.com/mastervanleeuwen/J-TrackGallery/releases/tag/0.9.35-fixup
