### ISSUE TITLE
Missing translation "My Tracks"

### ISSUE THREAD

**Issue by Wesmaster** [mastervanleeuwen/J-TrackGallery#79]
<?php echo $this->parseTemplate("headline", JText::_("My tracks"), "tracklist", null); ?>

Line 78 of views/user/tmpl/default.php

"My tracks" should be 'COM_JTG_MY_FILES'

**Comment by mastervanleeuwen** [comment]
Thanks for the detailed report. This is fixed in the following release:
https://github.com/mastervanleeuwen/J-TrackGallery/releases/tag/0.9.35-fixup
