### ISSUE TITLE
Category filter option

### ISSUE THREAD

**Issue by Alarcian** [mastervanleeuwen/J-TrackGallery#83]
Hello,

In the filter options, the filter for the category has a first option that states the text from "COM_JTG_CAT_SELECT". This option when selected seems to be seen as a category itself and uses that as a filter option, while it is no category itself.
Can this be fixed, or maybe that it is handled as selecting all categories as a filter or that it is a text above the actual category filter option?

Thanks

**Comment by mastervanleeuwen** [comment]
Good point; this is a leftover from when this field was a single selection list. Fixed in: https://github.com/mastervanleeuwen/J-TrackGallery/releases/tag/0.9.35-c
