### ISSUE TITLE
Joomla 5.1 Compatability

### ISSUE THREAD

**Issue by gcopping** [mastervanleeuwen/J-TrackGallery#87]
Hi,

Can you please tell me if J!TrackGallery 0.9.34 is compatible with J5.1?

Thanks in advance,

Gary

**Comment by mastervanleeuwen** [comment]
Hi Gary,

Yes, J!Trackgallery should work with Joomla 5.1. The demonstration website: https://jtrackgalleryj4.gta-trek.eu/index.php/en/ uses automatic updates for Joomla and is currently at Joomla 5.1. I have not specifically tested version 0.9.34, so I would suggest you update to the latest version of J!trackgallery: https://github.com/mastervanleeuwen/J-TrackGallery/releases/tag/0.9.35-e to avoid problems, but I am not aware of any specific Joomla-5 issues also with 0.9.34.

Best regards, Marco.

**Comment by gcopping** [comment]
Hi Marco,

Thanks for the info - just 1 further question. When I go to your github
link I am presented with 8 potential downloads - which 1 do I take?

Regards,

Gary

**Comment by mastervanleeuwen** [comment]
Hi Gary,

The main file is the 'component' file: 'com_jtg.zip'. There is also a plugin and three modules that can be used for specific tasks, e.g. showing a map in an article/regular Joomla! page; they rely on the 'component' to store the tracks (component, module and plugin are specific Joomla-jargon). In case you are interested, there is a bit more explanation here: https://mastervanleeuwen.github.io/J-TrackGallery/#description-of-the-packages

Best regards, Marco.
