### ISSUE TITLE
jttrack download .gpx file from visitors

### ISSUE THREAD

**Issue by LOM44** [mastervanleeuwen/J-TrackGallery#88]
Hi,
i use Jtrack gallery on Joomla 4.
is it possible for visitors to download original .gpx file by cliking on a icon ?
Thanks

**Comment by mastervanleeuwen** [comment]
Hi,
Yes, you can give permission to unregistered users for front-end downloads, as described here: https://mastervanleeuwen.github.io/J-TrackGallery/configuration.html#permissions
When this is activated, a button is shown for download (different formats are possible; this is configured in the settings).
Best regards, Marco.

**Comment by LOM44** [comment]
Thanks
 
 
  
   Lom informatique
  
  
   Olivier Massé 
  
  
   24 rue du champ de foire (Centre bourg) 
  
  
   44119 Treillières
  
  
   
   
   
  
  
   Https://www.lom-informatique.fr
   ***@***.***
   Tel : 06 51 05 38 28
