### ISSUE TITLE
Pressing gpx download button takes me back to my joomla homepage

### ISSUE THREAD

**Issue by jvevfvf** [mastervanleeuwen/J-TrackGallery#9]
Hi Marco,
I've setup jtg on my bushwalking club website, and its been working well. 
Something's changed (adding a new unrelated extension maybe?) and now the download button isn't working.
I've tried adding debug to the jtg.php file to see if its being called, as well as the download controller, but i don't see either being called.

Everything else seems to be working fine - i can add new tracks, update, delete, add comments etc

I'm a bit lost on how to proceed.
Are you able to provide any guideance?
Thanks
Jeff

**Comment by jvevfvf** [comment]
i tried removing some of the duplicate option/controller/task parameters - they were specified both as query parameters and form fields, but no joy. I made them all either query or form, but still not working.

Request URL: https://www.mbwc.org.au//index.php?controller=download&task=download
Request Method: POST
Status Code: 303 
Remote Address: 43.241.54.246:443
Referrer Policy: strict-origin-when-cross-origin
cache-control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
content-length: 0
content-type: text/html; charset=utf-8
date: Tue, 20 Jul 2021 10:35:29 GMT
expires: Wed, 17 Aug 2005 00:00:00 GMT
last-modified: Tue, 20 Jul 2021 10:35:29 GMT
location: /home-page
p3p: CP="NOI ADM DEV PSAi COM NAV OUR OTRo STP IND DEM"
pragma: no-cache
server: LiteSpeed
X-DNS-Prefetch-Control: off
x-powered-by: PHP/7.3.29
:authority: www.mbwc.org.au
:method: POST
:path: //index.php?controller=download&task=download
:scheme: https
accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
accept-encoding: gzip, deflate, br
accept-language: en-GB,en-US;q=0.9,en;q=0.8
cache-control: max-age=0
content-length: 72
content-type: application/x-www-form-urlencoded
cookie: templateColor=blue; joomla_user_state=logged_in; jpanesliders_statistics_pane=0; 5c8e11cb3df1c7530228409567f12dee=b971a184f79c5c3b7bf462e500546e24; abaa743494a4f6672a541b5aee829089=59e3e58ebf23db3ec050458fd1634176
origin: https://www.mbwc.org.au
referer: https://www.mbwc.org.au/new-walks-library/files/file/215
sec-ch-ua: " Not;A Brand";v="99", "Google Chrome";v="91", "Chromium";v="91"
sec-ch-ua-mobile: ?0
sec-fetch-dest: document
sec-fetch-mode: navigate
sec-fetch-site: same-origin
sec-fetch-user: ?1
upgrade-insecure-requests: 1
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.164 Safari/537.36
controller: download
task: download
f2442ffa598ab36cde99fca830d7aacb: 1
format: original
option: com_jtg
id: 215

**Comment by mastervanleeuwen** [comment]
Hi Jeff,

Thanks for trying this out! In the latest 'pre-releases' on github, I made some changes to the permission system. These are now managed via the 'Global configuration' menu item on the left in the admin view; if you click it, and choose, 'J!Track Gallery' from the list on the left, there is a 'permissions' tab where you can can give everyone ('Public') permission to download. This is more in line with the standard way this works in Joomla!, so my plan is to keep it this way in future versions.

Let me know if this is not clear or does not work for you.

Best regards, Marco.

**Comment by mastervanleeuwen** [comment]
Hi Jeff,

Reading your message again, I realise that my reply is not quite addressing the issue that you can into. I had read to quickly and thought thet the download button does not show on your website, but according to what you write above it does.

Is the problem still there? If so, could you try to download a gpx file from my test website above? Which version of J!TrackGallery are you currently using? I have been working quite a bit on the code, and have put several test releases on github; maybe this was broken by accident in one of them. Are you updating using the tags on github, or do you use the Joomla update managed? The latter should be at version, 0.9.30. Which web browser are you using?

The link with controller=download&task=download looks OK to me; this calls the 'download()' function of the JtgControllerDownload; the code can be found in the file components/com_jtg/controllers/download.php.

Best regards, Marco.

**Comment by jvevfvf** [comment]
Hi Marco,
I couldn't get it to work using the existing button. I had to change the
button to:

   $download_buttons .= "<a class='btn' href='" .
JRoute::_("index.php?option=com_jtg&controller=files&task=download&id=" .
$this->track->id . "&dformat=original"
) . "'> $ext ". JText::_('COM_JTG_ORIGINAL_FILE') . "</a>";


and i had to move the download function to the files controller, and then i
also had to modify the download method to add the following line at the
bottom:

JFactory::getApplication()->close();


(Otherwise the download included the html header)

So its working now, but i'm not sure why it stopped working!

Thanks for responding anyway :-)
Cheers
Jeff

**Comment by mastervanleeuwen** [comment]
This is solved for now; I think that it should also work in the latest version. In case it recurs, please let me know and I will look at it in more detail.

Cheers, Marco.
