### ISSUE TITLE
Warning issued in latest pre release when adding a track

### ISSUE THREAD

**Issue by noelada** [mastervanleeuwen/J-TrackGallery#90]
Hi Marco,
I am getting Warning: Undefined property: JtgViewTrack::$tagids in G:\xampp\htdocs\DVBC\components\com_jtg\views\track\tmpl\form.php on line 121
Line 121 has $tagField->setValue($this->tagids);

Best wishes,
Noel.

**Comment by mastervanleeuwen** [comment]
Hi Noel, 

Thanks for the report. I included a fix in the rerelease of rc1 and it should be fixed in the latest pre-release as well:

https://github.com/mastervanleeuwen/J-TrackGallery/releases/tag/0.9.36-rc3

Best regards, Marco.

**Comment by noelada** [comment]
Thanks Marco,
Noel.
________________________________

**Comment by noelada** [comment]
Hi Marco,
Do you have any plans to allow Google Maps as an option in future - like GPS Tools by Shondalai ?
Best wishes,
Noel.


***@***.***>

**Comment by noelada** [comment]
Hi Marco,
Thanks for the reply. We are using Google maps and what3words for our activity locations because of the navigation facilities using Apple Carplay and Android Auto. If you manage to get Google maps working, we could navigate to the starting point on the JTRACK map. This would simplify our setup of walking activities, so please let me know of any progress.
Best wishes,
Noel.
________________________________

**Comment by mastervanleeuwen** [comment]
Hi Noel,

I have added som code for a button that opens a new tab to navigate to the start of the track with google maps. You can find this on my test/demo site:

https://jtrackgalleryj4.gta-trek.eu/index.php/en/track/sample-trek-valroc-secteur-1

Could you have a look and let me know whether this would serve your purpose? If so, I can finalise this and make it available. It should also be possible to show the tracks in google maps, but that requires a bit more work.

Best regards, Marco.

**Comment by noelada** [comment]
Hi Marko,
I downloaded and installed v0.9.36a but was unable to find the new option to enable. Is there a possibility something went wrong with the compile ?
Best wishes,
Noel.
________________________________

**Comment by mastervanleeuwen** [comment]
Oops, indeed, I forgot to update something. I recreated the release and verified that it works:

https://github.com/mastervanleeuwen/J-TrackGallery/releases/tag/v0.9.36a

Best regards, Marco.

**Comment by noelada** [comment]
Hi Marco,
It works a treat.
Thanks,
Noel.
________________________________
