### ISSUE TITLE
Display of the tracks

### ISSUE THREAD

**Issue by ClemSchn2** [mastervanleeuwen/J-TrackGallery#92]
Hello, I have a simple comprehension question. I have uploaded a GPS track and get various numbers displayed in circles. 

https://c-schnitzler.de/index.php/foto/fotowalks/kornsand

It's about the white numbers, e.g. the number 95 near the start and finish. Where do these numbers come from? (This part i answered by myself. sorry!)

I would also like to add my own waypoints. I can do this in Alltrails, for example. Can I then assign my own graphics to these waypoints? If so, how can this be done?

I would also like to display the tracks in tabs. 

Please see this example:
https://clemensschnitzler.eu/foto/fotowalks/211-rosenbluete-in-eltville-2.html

Unfortunately, the map is not displayed there. https://c-schnitzler.de/index.php/foto/fotowalks/kornsand

Is this still possible? If so, what do I have to do?

Many thanks for your help

Clemens

**Comment by mastervanleeuwen** [comment]
Hi Clemens,

Thanks for your message. The blue circles with white numbers are distance indicators. You can switch these off in the configuration menu for the track view (under System Menu -->  Global Configuration --> J!TrackGallery).

It is possible to use your own custom icons for waypoints in J!TrackGallery. Some (brief) instructions are given here: https://mastervanleeuwen.github.io/J-TrackGallery/frontend.html#waypoint-icons
Don't hesitate to ask again in case something does not work.

Best regards, Marco.

**Comment by ClemSchn2** [comment]
Thank you for your answer.

When I load a track via plugin into an article and activate show_graph=1 I get an error message. 

https://clemensschnitzler.eu/touren/tagestouren/312-zum-kornsand.html

<img width="774" alt="Bildschirmfoto 2024-10-25 um 08 48 18" src="https://github.com/user-attachments/assets/9932989f-e994-46f8-8c13-4fe5b4d5ed1f">

As soon as I set show_graph=0 I get the track displayed. What could be the reason for this?

Regards

Clemens

**Comment by mastervanleeuwen** [comment]
Hi Clemens,

Thanks for the report. That is strange. Could you send me the full syntax
that you use for the plugin in this case? The arguments should separated by
a comma. Maybe you are using a different character?

Best  regards, Marco.

**Comment by ClemSchn2** [comment]
No, the syntax was fine! I found the error after a long search. I was using an extension to load the Googlefonts internally. This causes the error. After I uninstalled it, (almost) everything worked.

https://clemensschnitzler.eu/touren/tagestouren/312-zum-kornsand.html

I have two tabs on this page. Gallery and map. When I load the page on the iPAD, everything is fine. When I switch from the Gallery tab to the Map tab, I have the buttons for operating the map and the elevation profile, but the map is not displayed, there is only a white area. If you then move the page up or down, the map also appears. 

As the maps on my website generally appear in tabs, it would be good if a solution could be found.

Best regards, Clemens
![IMG_1111](https://github.com/user-attachments/assets/c633cacc-7a95-464b-b8d9-e7c6b50ffb0e)

**Comment by mastervanleeuwen** [comment]
Hi Clemens,

Thanks for the report. The issue with the display in the tabs, seems to be a browser(-version) dependent issue. I tried it on my ipad (which has an older version of iOS) and also on a laptop with both safari and google chrome, and they all seem to work. Is the screenshot from an iPad? Which iOS version are you using?

Best regards, Marco.

**Comment by ClemSchn2** [comment]
The Screenshot is from an iPAD. The iOS Version was 18.0. On my Mac i have the same problem. The problem appears in Safari and Google Chrome browsers.

Best Regards, Clemens

**Comment by mastervanleeuwen** [comment]
Hmm, that is strange. I do not seem to be able to reproduce the problem. I wonder whether something is blocking javascript. Did you test whether the map-plugin works when you do not show the map in a tab?

Could you use the developer tools in the browser (on Google chrome this is in the menu on the upper right, when you klick the three vertical dots, and choose 'More tools -> Developer tools' to see whether there are any (javascript) warnings? I do get  this one:

<img width="493" alt="image" src="https://github.com/user-attachments/assets/6d80a72c-f5eb-4706-b7c8-d895344328cc">

which however does not seem to affect the display of the site. In the 'console' on the bottom right, I also see:
<img width="521" alt="image" src="https://github.com/user-attachments/assets/4b02e436-9028-4e3d-ae40-f52124a1b3c9">

Do you have any additional warnings/errors?

Best regards, Marco.

**Comment by ClemSchn2** [comment]
Hi Marco

I am not a programmer but I try. I get the following displayed at the top: 

￼


If I click on the exclamation mark in the triangle, these two messages are displayed further down:

￼

￼

I hope you can do something with it.

Best regards Clemens


Clemens Schnitzler
Am Schillertempel 14
65527 Niedernhausen

**Comment by mastervanleeuwen** [comment]
Hi Clemens,

Thanks for giving this a try. Unfortunately, the pictures are not
attached to this message. Can you try to copy (or drag-and-drop) them into
the issue page on github, instead of sending them by e-mail?

Best regards,

Marco.

**Comment by ClemSchn2** [comment]
Hi Marco,

i habe the pictures included in my last post.

Best regards, Clemens

**Comment by mastervanleeuwen** [comment]
Hi Clemens,

Thanks for posting the pictures. The warnings/errors there are harmless, I also see them on my system. I played around a bit more with different browsers and different systems, and every time the map displays well on my end, so I am not sure what is happening. Could you also click on the red flag with the cross and let me know what message is shown?

One more thing that you can try is to reload the page with command + shift + R or alt + shift + R, which will force refreshing the cache, which may help.

A few more questions to try and narrow down where the problem may be:

- Do the maps on my test page here: https://jtrackgalleryj4.gta-trek.eu/index.php/en/plugin display correctly for you?

- Do the maps show up properly in the backend when you look at the tracks/files?

- I also tried to show a track using the frontend; this link: https://clemensschnitzler.eu/index.php?option=com_jtg&view=track&layout=default&id=11  or https://clemensschnitzler.eu/index.php?option=com_jtg&view=track&layout=default&id=21 should normally work when the component is active. On your page, I don't get an error message, but also the information about the trail do not show. I am not sure whether that is a problem by itself.

- Are you using the latest version of the component and plugin: https://github.com/mastervanleeuwen/J-TrackGallery/releases/tag/0.9.36-rc3 ?

Best regards, Marco.

**Comment by ClemSchn2** [comment]
Hello Marco,

it seems to be the version. I have installed the version you linked and now it seems to be ok. 

If I have any more questions I will get back to you.

Best regards and have a nice Sunday

Clemens


Clemens Schnitzler
Am Schillertempel 14
65527 Niedernhausen
Telefon ‭+49 179 7725109‬

**Comment by mastervanleeuwen** [comment]
Thanks Clemens, I am glad that this is solved. Don't hesitate to post again in case you have questions or problems.

Best regards, Marco.
